Forbid dynlinking of previously-loaded units (MPR#4229, MPR#4839, MPR#6462, MPR#6957, MPR#6950)
ocaml/ocaml pull request #1063
Opened 2017-02-24 14:30 UTC by mshinwell

This patch forbids dynlinking of compilation units that have already been loaded (either as part of the main program or via a previous dynlink).  This appears to be sufficient to solve the problems described in the five Mantis issues in the title of this pull request.

In bytecode, it was previously possible to break type abstraction, since there is no implementation CRC for bytecode.  In native, it was also possible to produce segmentation faults, via various means.

It has previously been suggested that platform-dependent solutions such as `RTLD_DEEPBIND` on glibc systems might be sufficient to solve these problems.  @chambart and I discussed this and it appears not to be the case: for example suppose there is some module `N` that generates fresh names.  `A` depends on `N` in the main program.  We dynlink `B` which also depends on `N`.  Further, `B` passes values made in `N` to `A`.  Whilst under `RTLD_DEEPBIND` the code of `B` successfully references its own copy of `N`, it passes values to `A` that could break invariants of `A`'s copy of `N` if they were to flow into there---and they might.  It seems safer to just be conservative.

@chambart and I discussed whether this new restriction would be problematic for authors of plugin systems that might end up loading modules more than once.  However we believe these problems can be solved by such systems using their own caching layer that can catch the new error value returned (`Dynlink.Error(Module_already_loaded ...)`).

A further improvement would be able to effectively incorporate such caching into the dynlink system itself such that, for example, if a module had already been dynlinked then some handle to that module could be returned.  Such a handle would naturally be a corresponding first class module.  Some of this work is already in GPR#100, although that does not include the protections introduced by this pull request.  @chambart will follow up about that.

It is possible that there remains one problematic situation: a module that tries to load itself whilst it is being initialised.  @chambart is checking this now.

2017-02-24 14:53 UTC, lpw25 commented
I think that RTLD_DEEPBIND could still be useful for the `loadfile_private` case. Your problematic example relies on there being a module `A` in the non-private linked modules which has `N` in its interface dependencies. This can be avoided with the rules:

- A module can only be linked publically if there is no other module with that name already linked publically

- A module can only be linked privately if there is no other module with that name linked publically, or mentioned in the interface dependencies of a module linked publically.

This would be a useful rule to support (on platforms with RTLD_DEEPBIND or equivalent) since it allows you to load plugins without having to worry if they conflict with each other -- only whether they conflict with the main program.

2017-02-24 15:11 UTC, mshinwell commented
After looking at MPR#4208 it looks like the `dynlink.ml` code needs a bit more work, e.g. due to `prohibit`.  It's also not immediately obvious whether `loadfile_private` is going to be safe at present even after MPR#4208 is fixed.  The easiest solution seems like a separate table of all modules ever loaded, which I'll investigate in due course.

2017-02-24 15:14 UTC, mshinwell commented
@lpw25 Yes, perhaps the rules could be refined to take into account the private case.  However it isn't clear to me whether it's worth spending the time to implement and test that, especially if it only works on a subset of platforms.  At the least I think we should probably get the basic fix in first before relaxing it, given how long some of these issues have been open.  Other opinions on the benefit of a more precise treatment would be welcome.

2017-02-25 08:21 UTC, xavierleroy commented
Thanks for getting the ball rolling on this long-standing issue.  Maybe @maximedenes and the Coq dev team wish to follow the discussion, as Coq is a heavy users of plugins that don't respect any naming discipline :-) and will be broken by the proposed solution.

2017-02-27 08:45 UTC, maximedenes commented
@xavierleroy thanks for drawing my attention to this patch. I don't expect so much trouble because nowadays, Coq plugins are packed (as in `-pack`). Not sure what happens when we play the same `Require` multiple times, though. I'll do a quick test and give feedback.

2017-02-27 09:22 UTC, mshinwell commented
@maximedenes Do you use natdynlink or the bytecode version?  If testing, it's probably best to use the native version with this patch at the moment, since the bytecode version may need a few tweaks (though it should approximately work).

2017-02-27 10:07 UTC, maximedenes commented
What is the easiest way to get camlp4/camlp5 compiled for ocaml with this patch? It is required for testing Coq plugins.

2017-03-06 10:07 UTC, diml commented
@maximedenes, for camlp4 I think the easiest way it is build it by hand from the git repository

2017-04-10 14:30 UTC, mshinwell commented
@maximedenes Has there been any progress on testing this patch?

2017-04-10 14:43 UTC, maximedenes commented
Oh! I thought I had sent a partial report, sorry.

I could only devote a few minutes to it, but I can already say that this patch breaks the compilation of Coq's stdlib. It is surprising, but could be explained if the behavior of some static initializers (code like `let _ = register...` at toplevel in dynamically loaded units) has changed in some way.

I can investigate more and report next week.

2017-04-24 13:40 UTC, mshinwell commented
@maximedenes Was that when running bytecode or native code?

2017-04-25 12:01 UTC, maximedenes commented
I tested a bit more, and the incompatibility I was mentioning is in fact already present in the base commit of this PR (sorry, I should have checked earlier). So not directly related to this PR, but it prevents me from testing properly. I'll try with 4.05 beta 3 and a recent 4.06 to see if rebasing this PR could help.

2017-04-26 07:59 UTC, maximedenes commented
@mshinwell I was running native code.

The failure is in fact unrelated, so I'll try again with a rebased version of this PR.

So far, testing did reveal that we link twice a camlp5 module, but it is easy to fix on Coq's side.

2017-04-26 08:54 UTC, maximedenes commented
Ok, so after rebasing, I confirm that modulo a small fix, Coq compiles fine with this PR, and plugins are usable. I tested only native code.

2017-04-26 15:47 UTC, mshinwell commented
OK, that's good news, thanks.  I need to do some more careful work on the bytecode part of this PR, but will try to do that soon, and then it can be considered further.

2017-05-02 15:03 UTC, chambart commented
I did check various self loading situations and couldn't come up with any failing one. Not that there isn't any possibility, but this would certainly not appear by surprise.

2017-05-02 15:06 UTC, chambart submitted a review, later dismissed
This effectively checks the presence of previously loaded modules. A test exercising it might be useful. I can provide it.

2017-05-02 15:16 UTC, mshinwell commented
I actually noticed a bug in this and the bytecode version needed some more work (as per previous conversation with @chambart ).  Whilst looking at that the large amount of duplicated code made me think that we can probably make this more robust with a bit more refactoring and sharing of code, which I'm working on now.  I will post here again once it's ready.

2017-05-02 15:19 UTC, mshinwell commented
@alainfrisch In the existing `natdynlink.ml` file there is a conditional which circumvents various checks if the name of a compilation unit being loaded happens to match the name of a predefined exception.  Leo and I experimented with this and couldn't find why this restriction, which appears to introduce an unsoundness, would be required.  Could you explain?  (As far as I can tell from `git` this is your code.)

2017-05-05 14:43 UTC, mshinwell commented
@chambart Would you be able to take a look at this version?  This now passes the test suite although I need to do a pass of review myself.  Adding the test case you suggest would be appreciated.

This pull request refactors the `dynlink` library by introducing a new `Dynlink_common` module.  The implementation of this module is based on the old `natdynlink` implementation; in particular it uses  maps rather than hashtables, which should solve MPR#4208.  It has checks which should prevent a module being dynlinked if it is already loaded, which should solve the various other Mantis issues listed above.  It does not contain the checks in the old `natdynlink.ml` concerning the names of exceptions, since they appear to be unsound.

This patch also removes the deprecated functions in the interface and the `digest_interface` internal function (I grepped OPAM for real uses of the latter and didn't find any).  I haven't surveyed usage of the deprecated functions, but given that some of them appear to have been deprecated I think it was 15 years ago and others deprecated about 9 years ago, they seem ripe for removal.

I hope that overall this produces a significant increase in robustness and maintainability for this library.

I had a long struggle with the various makefiles and the requirement that programs using `dynlink.cma` don't need compilerlibs too.  Care is thus taken to ensure that `dynlink_common.ml` only depends on the stdlib.  The dynlink code is built no fewer than three times (in `otherlibs/dynlink/`, in `driver/` and in `debugger/`)!

I would like to tidy the formatting of these files, which is currently rather inconsistent; this can be done as a separate changeset after the main review is done.

The diff for this PR is probably best read using patdiff.

2017-05-09 14:02 UTC, alainfrisch commented
> In the existing natdynlink.ml file there is a conditional which circumvents various checks if the name of a compilation unit being loaded happens to match the name of a predefined exception.

Probably some left over of a work-around required at that time, where builtin exception global identifiers were recorded in ui_imports_cmx.

FTR, this was introduced in:

http://caml.inria.fr/cgi-bin/viewvc.cgi/ocaml/branches/natdynlink/otherlibs/dynlink/natdynlink.ml?r1=7893&r2=7894&pathrev=8477&

apparently to make Camlp4 compile.  This can probably go away now.

(On a related note: https://caml.inria.fr/mantis/view.php?id=3829 )

2017-05-09 14:16 UTC, mshinwell commented
MPR#3829 appears fixed, so I've closed it.  We also experimented the other day with various scenarios involving compilation units with the same names as predefined exceptions and couldn't get anything to fail.

2017-05-09 14:35 UTC, alainfrisch commented
MPR#3829 is actually not fixed, I've reopened and added a slightly modified example.

2017-05-12 13:52 UTC, stedolan commented
> It has previously been suggested that platform-dependent solutions such as RTLD_DEEPBIND on glibc systems might be sufficient to solve these problems. @chambart and I discussed this and it appears not to be the case: for example suppose there is some module N that generates fresh names. A depends on N in the main program. We dynlink B which also depends on N. Further, B passes values made in N to A. Whilst under RTLD_DEEPBIND the code of B successfully references its own copy of N, it passes values to A that could break invariants of A's copy of N if they were to flow into there---and they might. It seems safer to just be conservative.

This explains why it is wrong for a dynlinked plugin to contain a copy of a module that is part of the main program. What about the case when two dynlinked plugins both contain a copy of the same module, which the main program does not contain? I would expect this to work when I load the plugins via `Dynlink.loadfile_private` - that seems to be what this function is for.

Does this patch support such usage?

2017-05-24 15:32 UTC, mshinwell commented
I've noticed that an important piece of this patch appears to be missing; I will fix that and then think further about @stedolan 's comment.  (I think the answer is that we could support such uses so long as the platform supports `RTLD_DEEPBIND`.)

2017-05-24 15:38 UTC, stedolan commented
> I think the answer is that we could support such uses so long as the platform supports `RTLD_DEEPBIND`.

I don't understand why `RTLD_DEEPBIND` is needed for the usage I described. Why isn't the standard flag `RTLD_LOCAL` (which is the default behaviour of `dlopen`, and currently used by `loadfile_private`) sufficient?

2017-05-24 16:19 UTC, mshinwell commented
I was kind of thinking you'd want complete isolation, so that if the plugin defined some other module that happens to be in the main program, there wouldn't be a clash.  I think you need `RTLD_DEEPBIND` for that, but if you're willing to live without that, we could have an intermediate level of isolation (perhaps the default) whereby plugins may contain modules that aren't in the main program but do clash on names across plugins.  That seems fine.

2017-05-24 16:28 UTC, lpw25 commented
I think if you allow multiple plugins containing modules with the same name then you'll need a slightly stricter check. At the moment the check prevents you from loading a module with the same name as one that was linked into the main program, but I think you would need to expand that to include any modules "imported" by the main program but not actually linked.

For example, the main program might have a module `A` containing a value `r` with type `B.t ref` even though the program does not link `B` into it. In this case, two plugins might both have different `B` modules (with the same `.cmi` digest but different implementations) and put different types of values into `r`.

2017-06-29 11:47 UTC, mshinwell commented
I think this is now ready for a first pass of code review. @lpw25 has volunteered.  Some of the main features:
- It should now be sound.  Lots of tricky cases have been carefully thought about.
- Much code has been shared between bytecode and native dynlink, with some error messages harmonised too.
- A fix for a self-initialization problem in natdynlink (when a main program loads a plugin P which has an initializer that loads a plugin Q which in turn has an initializer that references P).
- An improved interface for access control.
- The long-deprecated functions have been removed.

Where possible I have added the test cases from the various Mantis issues about dynlink to the testsuite.  They are all run both for bytecode and native even if the original reporters did not do so.

2017-09-23 17:10 UTC, xavierleroy commented
What's the status on this PR?  Could we plan it for 4.07?

2017-09-25 07:13 UTC, mshinwell commented
@xavierleroy Sure.  @lpw25 is going to review it when he's back from vacation.

2017-12-20 17:45 UTC, xavierleroy commented
This GPR is slowly rotting away (no action since Sept), and that's sad because it's addressing a very serious issue.  Could we please have @lpw25's review and perhaps some more eyeballing as well?

2017-12-21 10:34 UTC, lpw25 commented
I should have time in January to look at this. Anyone else should feel free to review before then if they have the time.

2018-02-09 11:54 UTC, XVilka commented
Are there any updates on this one?

2018-02-12 08:06 UTC, mshinwell commented
It really is on the stack for review soon; unfortunately some important type system related work scheduled for 4.07 is getting in the way.

2018-07-24 10:05 UTC, lpw25 requested changes
I've reviewed this now. There were a few things that needed changing in order to match the specification in Mark's description. I've turned these changes into a pull request against this branch (https://github.com/mshinwell/ocaml/pull/10). Once Mark has reviewed and merged those changes into this PR then I think it is ready to be merged upstream.

2018-11-08 13:30 UTC, nojb commented
The bug came up again today in the `caml-list`... It would be great to have this in 4.08, if possible.

@mshinwell: could you review @lpw25's PR? If you merge that, I could do the rebase afterwards if you are pressed for time.

2018-11-08 13:39 UTC, mshinwell commented
@nojb Thanks for the offer, I'm looking at this today.

2018-11-08 15:46 UTC, nojb commented
@mshinwell are you satisfied with the patch as it is? If so, I will rebase in the next few days.

2018-11-08 16:16 UTC, mshinwell commented
@nojb I'm doing everything, but thanks.

2018-11-08 17:21 UTC, mshinwell commented
Assuming this passes CI it is ready to merge.  @lpw25 please approve.

The documentation in the relevant dynlink interface file has been updated to reflect the new behaviour.

For the record: we do not implement any `RTLD_DEEPBIND` support, but we think it is the case that the only thing that might stand in the way of such support is the lack of cross-platform compatibility.  All of the potential (un)soundness issues should be taken care of by this patch as it stands now.

2018-11-08 17:23 UTC, nojb commented
I think you will need to port your tests to `ocamltest`.

2018-11-08 17:24 UTC, mshinwell commented
I'd rather port the tests to `ocamltest` later, since we are very short of time.  Is this a hard requirement?  (I was not aware it was, though I may be mistaken.)

2018-11-08 17:32 UTC, gasche commented
Well we don't have any other tests than ocamltest tests anymore, so yes I think this would need to be in ocamltest.

2018-11-08 18:13 UTC, lpw25 commented
I didn't realize everything had been switch over. Shouldn't all the `Makefile.common` stuff be removed now then? That would stop people from adding more non-ocamltest tests.

2018-11-09 15:40 UTC, mshinwell commented
Thanks to the hard work of @nojb the tests have been ported to ocamltest.  I've added an interface file for `Dynlink_common` along with various other miscellaneous clean-ups and formatting improvements.  This should now be good to go.

2018-11-09 17:08 UTC, lpw25 approved these changes
All my requested changes have been dealt with. Apparently there is an issue with the tests spuriously failing when backtraces are enabled -- as they are on travis for the flambda build. Once that is fixed then this is ready to go.

2018-11-12 08:53 UTC, nojb commented
Anyone remembers why we activate exception traces unconditionally when running the FLAMBDA CI? It would seem better to only activate them for specific tests.

2018-11-12 17:45 UTC, mshinwell commented
Right, the test problems are hopefully fixed.  Let's see...

2018-11-13 08:39 UTC, nojb commented
- For Travis, there was a timeout on the FLAMBDA job; I restarted it.
- On Windows, the test `lib-dynlink-csharp` needs updating (I think it still calls `Dynlink.init`).

2018-11-13 09:46 UTC, mshinwell commented
@nojb Thanks, I've removed that line from the `lib-dynlink-csharp` test.

2018-11-13 12:59 UTC, mshinwell commented
I think I know what's causing the slowdown with Flambda - investigating.

2018-11-14 16:31 UTC, mshinwell commented
This should now be fixed (thanks to @dra27 for help).  The problem was that the `.ml`-only `_intf` file which now lives in `otherlibs/dynlink/` was causing full recompilation of `ocamlopt` when building the `tools/` directory: running `ocamlopt` on the `.ml` file was re-writing the `.cmi`, thus invalidating `ocamlopt` itself (since the `.cmi` was then older than the corresponding `.cmo`).

A substantial number of hours were wasted chasing down this problem, which I suspect would not have existed if we were using `dune`, not to mention the surprisingly large amount of time it took to fix the build system for the relatively minor adjustments to the structure of `otherlibs/dynlink/`.

I timed the latest revision on my own machine and it appears to have solved the problem.  This is OK to merge if the CI passes.

2018-11-14 20:58 UTC, dra27 commented
One dull housekeeping thing - does `.gitignore` need updating, or are the files generated in `driver/` already there?

2018-11-15 10:57 UTC, mshinwell commented
@dra27 I've fixed `.gitignore`, good thinking.  Hopefully this will now pass CI.

2018-11-15 12:39 UTC, merged

2018-11-15 12:39 UTC, nojb commented
Merged, thanks everyone!

2018-11-24 14:08 UTC, ejgallego commented
Dear Ocaml devs, see https://caml.inria.fr/mantis/view.php?id=7876 which could be related to this PR.

2018-12-12 14:51 UTC, damiendoligez commented
Looks like this PR broke the cygwin64 CI (which currently does not support dynlink). See https://ci.inria.fr/ocaml/job/main/flambda=false,label=ocaml-cygwin-64/833/console

You can reproduce the bug on other architectures by configuring with `-no-shared-libs`.

AFAICT it's simply that the `nodynlink.ml` file is out of date wrt the rest of the patch.

cc @mshinwell @lpw25 @nojb @chambart

2018-12-12 14:53 UTC, mshinwell commented
Ack

2018-12-12 15:10 UTC, mshinwell commented
@damiendoligez Please see #2197

2019-08-11 14:42 UTC, garrigue commented
This indeed did break old versions of Coq, including 8.9.1: #8868.

2019-10-18 17:41 UTC, gadmm commented
I would like to offer a small nitpick and advice about backwards-compatibility.

This commit removed the deprecated function [Dynlink.init]. It was commented as deprecated since 2008, however there had been no warning at compilation. Moreover, it seems that the issue was properly caught by the test `lib-dynlink-csharp`, but not understood as such. The result is unexplained breakage of legacy code with no documented evolution path (see https://github.com/ppedrot/ocaml-melt/pull/1). The adverse effect is that although the solution is trivial (remove the call), this results in disproportionate time spent by the non-author user looking up for a solution, reading git commits and github PRs, to find what is the appropriate action.

As a suggested alternative, it would have been possible to have deprecation warnings in place in 2008 with suggested evolution path, or, even simpler for everybody, keep providing `init` with the current PR with a dummy implementation. Indeed, AFAIU there was no imperative to break legacy code.

(cc @tabareau)