Bugfix for `caml_ba_alloc` GC work tracking
ocaml/ocaml pull request #11022
Opened 2022-02-16 17:04 UTC by stedolan

When the `caml_ba_alloc` allocates memory for a bigarray, it calls `caml_alloc_custom_mem` with nonzero size, instructing the GC to speed up. When it is given preallocated memory, it uses `size = 0`, causing no GC speedup.

This criterion is slightly wrong: if given preallocated memory with the `CAML_BA_MANAGED` flag set, then the lifetime of this memory is managed by the GC, and the GC should speed up.

This patch passes the size when either `caml_ba_alloc` does the allocation itself, or `CAML_BA_MANAGED` flag was set. This means that the GC speeds up iff the GC now has more memory to manage.

cc @ahh (who reported the issue)

2022-02-16 18:36 UTC, nojb commented
> This patch passes the size when either `caml_ba_alloc` does the allocation itself, or `CAML_BA_MANAGED` flag was set. This means that the GC speeds up iff the GC now has more memory to manage.

Sorry for the naïve question, but if `caml_ba_alloc` is passed a block of memory with the `CAML_BA_MANAGED` flag set, in what sense is there "more memory to manage"? Since we are not really allocating any new out-of-heap resources, I'm wondering how to think about it...

2022-02-17 15:20 UTC, damiendoligez commented
The `CAML_BA_MANAGED` flag gives the GC responsibility for deallocating this memory, as if `caml_ba_alloc` had called `malloc` itself, so this change totally makes sense.

2022-02-17 15:25 UTC, damiendoligez requested changes

2022-02-17 15:25 UTC, damiendoligez commented on runtime/bigarray.c
> +                              (flags & CAML_BA_MANAGED) ? size : 0);
You're supposed to mask with `CAML_BA_MANAGED_MASK` and compare with `CAML_BA_EXTERNAL` or `CAML_BA_MANAGED`. (compare `caml_ba_finalize` around line 146)

```suggestion
  if ((flags & CAML_BA_MANAGED_MASK) == CAML_BA_EXTERNAL) size = 0;
  res = caml_alloc_custom_mem(&caml_ba_ops, asize, size);
```

2022-02-21 14:09 UTC, stedolan commented on runtime/bigarray.c
> +                              (flags & CAML_BA_MANAGED) ? size : 0);
Thanks, fixed. (I also removed a redundant initialisation a couple of lines up)

2022-03-01 12:11 UTC, stedolan commented
(`Changes` conflict now fixed)

2022-03-02 15:41 UTC, damiendoligez approved these changes
Looks good now.

2022-03-02 16:56 UTC, merged

2022-03-15 19:44 UTC, lpw25 commented
I think that this PR has bad behaviour for `caml_ba_sub`. I think that taking a subarray of a managed bigarray will now cause GC speedup, and I think that I am seeing this effect in some real programs (we've backported this patch to our internal compiler).