Ocamldoc: no -title, no empty <h1> in html
ocaml/ocaml pull request #1103
Opened 2017-03-12 16:31 UTC by pirbo

PR#6928 discussion contains 2 points: 
- Do not generate an empty intro `<h1>` when ocamldoc is launched without `-title`.  
> [this] does seem like an unconditional improvement
 @Octachron

This is what this patch implements.

- Do not introduce a `<h1>` with the content of `-title` at all when `-intro` is specified to respect `-intro` documentation:
> Use content of file as ocamldoc text to use as introduction (HTML, LATEX and TeXinfo only). __For HTML, the file is used to create the whole index.html file__

I have no dog in this fight... (Maybe, the mistake is just in the description of `-intro`)

2017-03-12 17:00 UTC, Octachron requested changes
Thanks for the nice PR! I have few remarks that need to be addressed, but overall it is a nice improvement and we can left the other points discussed in the PR for later in the 4.06 cycle.

2017-03-12 17:00 UTC, Octachron commented on Changes
> +- PR#6928: ocamldoc, do not introduce an empty <h1> in index.html when
This should go to the tools section since it is an user-visible change.

2017-03-12 17:00 UTC, Octachron commented on ocamldoc/odoc_html.ml
> +              bs b "</h1>\n" in
Sorry for the nitpicking but the `let () = …  in` style is quite at odd with the rest of the file, even more so when printing the title. I am little bit worried that potential future readers would be left wondering why the `;` operator was so violently avoided in this specific part of the code.

2017-03-12 17:37 UTC, pirbo commented on Changes
> +- PR#6928: ocamldoc, do not introduce an empty <h1> in index.html when
Of course, it is a no-proofreading-after-`git rebase` mistake...

2017-03-12 17:43 UTC, pirbo commented on ocamldoc/odoc_html.ml
> +              bs b "</h1>\n" in
Agreed and corrected but this one was intentional. `;` precedence is a nightmare for me and after having been too many time by
```
if something then foo;
bar
```
that even tuareg wrongly indent. I decided to ban `;` :-) (I don't find `let () = ... in` less odd than the `(match ...); ...` I had to make here. Anyway, taste and colours, sorry to not respect the format of the fil I edited...)

2017-03-12 18:44 UTC, Octachron approved these changes

2017-03-12 18:45 UTC, Octachron commented on ocamldoc/odoc_html.ml
> +              bs b "</h1>\n" in
Thanks for your editing! I can sympathize with your stylistic preference, but I would rather avoid mixing local style change with semantic changes.

2017-03-12 18:51 UTC, Octachron commented
The changes looks fine to me, I will merge after CI tests pass.
I wondered if this change should go into 4.05 ; but I think  it would be better to collect all ocamldoc html output changes in 4.06 .

2017-03-12 19:45 UTC, merged

2017-03-12 19:46 UTC, Octachron commented
Merged, thanks again.

2017-03-13 13:12 UTC, pirbo commented
Thank you for the nice and fast review.
I don't have any opinion upon 4.05 integration. The bug was filled during 4.02 cycle... My motivation was to stop seeing this triviality indefinitely postponed version after version.