minor bugfix in caml_reallocate_minor_heap
ocaml/ocaml pull request #11046
Opened 2022-02-21 23:09 UTC by gasche

This PR documents the minor heap layout and fixes a minor bug in the "decommit" logic of caml_reallocate_minor_heap.

2022-02-22 05:08 UTC, kayceesrk approved these changes
Looks good to me. 

To summarize, the bug was that the memory decommit was being applied to the entire reserved area of a domain's minor heap, and not just to the committed area. This PR fixes the bug by decommitting only the committed area.

2022-02-22 10:41 UTC, stedolan requested changes

2022-02-22 10:41 UTC, stedolan commented on runtime/domain.c
> +      (void*)domain_state->young_end - (void*)domain_state->young_start);
Subtraction of two `void*` pointers is not standard C (although is accepted by several compilers), because it's unclear how many `void`s there are supposed to be between two addresses. If you want the distance in bytes, cast to `char*` instead.

2022-02-22 10:44 UTC, gasche commented on runtime/domain.c
> +      (void*)domain_state->young_end - (void*)domain_state->young_start);
Thanks! I was wondering, but I followed the `(void*)` style above. Will fix.

2022-02-22 10:48 UTC, gasche commented on runtime/domain.c
> +      (void*)domain_state->young_end - (void*)domain_state->young_start);
Done, thanks for the review!

2022-02-22 10:49 UTC, stedolan approved these changes

2022-02-22 12:56 UTC, merged

2022-02-25 08:16 UTC, gasche commented on runtime/domain.c
> +      && domain_state->young_end < (value*)domain_self->minor_heap_area_end));
Note to self: this debug assertion is too strict (it should be `<=` not `<`): `young_end` can be equal to `minor_heap_area_end` when the minor heap size is precisely `Minor_heap_max`. I pushed this change directly in f36e5f28aae33b0204760af3307abebf6aa82219.