Gc stats: major collections count
ocaml/ocaml pull request #11123
Opened 2022-03-17 22:54 UTC by gasche

Currently there are two different counters of major collection cycles:
- `caml_major_cycles_completed`, which is a global variable incremented at the completion of each GC cycle, used by the runtime system for various "check that at least one cycle has happened" conditions
- `Caml_state->stat_major_collections`, which is a per-domain count that is also incremented at the completion of each GC cycle, and is only used for statistics reporting (`(Gc.quick_stats()).major_collections`).

Unfortunately, `Caml_state->stat_major_collections` has a fairly weird behavior:
- during each GC cycle, all participating domains increment their `Caml_state->stat_major_collections` counter
- morally this means that this counter counts the "number of major cycles that this domain participated in"
- but because the `domain_state` data of terminated domain is reused when spawning new domains, the `stat_major_collections` count of a just-spawned domain may be non-zero.

This PR gets rid of `Caml_state->stat_major_collections` and uses the more principled `caml_major_cycles_completed` global value instead in reported statistics. The meaning of this value is clear, it is the number of major GC cycles completed since the program started -- this is exactly what the documentation says.

In local experiments I checked that during non-multicore runs (of the sequential test `weaklifetime.ml`), the value of `caml_major_cycles_completed` and `Caml_state->stat_major_collections` is the same on each `Gc.quick_stats()` call.

cc @Engil

2022-03-22 16:42 UTC, abbysmal commented
Hello,

I think this is a fair simplification and cleanup.
One could argue that we could keep the idea of a domain-local count, and just fix the implementation (by zeroing it).
Since the domain-local vs global stats story is not quite clearly defined yet, I think that going for the simpler semantic for now is the best.

2022-03-22 16:44 UTC, gasche commented
I'm also not sure what is the value of the domain-local count; this is not a per-domain count in the sense that (unlike heap stats for example) summing the stats of all active domains does not have any meaning, it would incorrectly duplicate counting the same major collection several time.

2022-03-22 16:46 UTC, gasche commented
(Did you mean to Approve or Review this PR?)

2022-03-22 16:46 UTC, Engil requested changes
I think one adjustment is missing at `testsuite/tests/c-api/alloc_async_stubs.c`.
I didn't look into it but it is odd that this testcase does not crash with the removal of this field?

2022-03-22 16:52 UTC, Engil commented
Ha, it is actually disabled!
Due to https://github.com/ocaml/ocaml/pull/8897 (I do not quite remember the history for disabling this testcase, this is probably worth looking into elsewhere.)
It is probably worth at least making sure the test compiles with this PR changes.

2022-03-22 22:10 UTC, gasche commented
I pushed a new commit that fixes the C stubs of this disabled test.

This may be realize that there might be a backward-compatibility issue with completely removing `Caml_state->stat_major_collections`. This variable has been defined for many releases of OCaml. I'm assuming it was for internal use only, and github search only turns out myriads of copies of the runtime code, but is there a reason to be worried here? (cc some people who may know what compatibility guarantees we want to provide for `Caml_state` fields: @xavierleroy, @kayceesrk, @gadmm.)

2022-03-23 09:35 UTC, sabine approved these changes
Looks good to me.

It's unclear what exact use case a "how often did this domain participate in major gc" counter has. Relying instead on the existing `caml_major_cycles_completed`, and adjusting the semantics of the code to what the manual says makes sense to me.

The removal of the domain state field `stat_major_collections` is a useful simplification, as it makes the global nature of the counter more obvious.

2022-03-23 13:41 UTC, gadmm commented
@gasche Historically all `Caml_state` fields are internal, except `compare_unordered`. This is not documented (it should be, in order to avoid delicate situations in the future; this is #9179).

2022-03-23 14:34 UTC, gasche commented
Thanks! This sounds good to merge then, if @Engil approves. (I updated the skipped test to compile again.)

2022-03-23 14:58 UTC, abbysmal approved these changes

2022-03-23 15:02 UTC, Engil commented
LGTM, thanks for the adjustments.
I took a look at `opam-grep` as well and I seem to only find vendored runtime files, or vendored bindings to the ocaml-runtime (more specifically the rust crate `ocaml-sys`, which is broken on trunk anyway).
So I think it is fine to merge this as is.

2022-03-23 15:02 UTC, merged

2022-03-23 15:04 UTC, gasche commented
@Engil Thanks! Now you might be interested in #11124 :-)