Move last finalisers book keeping to the end of minor gc
ocaml/ocaml pull request #12001
Opened 2023-02-08 16:44 UTC by Engil

This PR is an implementation of @kayceesrk 's suggestion in #11995

This commit implements a fix on how last finalisers are updated during the minor cycle.

Currently, the book keeping is done during the minor cycle, before the values are promoted.
As a result, last finalisers are wrongly run after the end of the minor cycle even is the value is promoted (and as such, live), precisely because the book keeping did not account the the promoted values.

The fix suggested by @kayceesrk is to move said book keeping to the end of the minor gc cycle, and can be done outside of the last barrier for the minor cycle, as a domain will only process finalisers within its own minor heap.

2023-02-08 16:54 UTC, Gbury commented
Would it make sense to add a test to the testsuite ?

2023-02-09 04:43 UTC, kayceesrk commented
The fix looks reasonable. 

Can you add the test from #11995 to the testsuite?

2023-02-09 10:22 UTC, sadiqj approved these changes
This bug has been present since the first stop-the-world minor implementation - I'm very surprised nobody has hit it until now. It does require you to have a finalised value that is only reachable via the local roots, which is probably a rare occurrence.

The fix looks correct.

2023-02-09 10:26 UTC, sadiqj requested changes
It's just occurred to me this might not be correct. We do this after the final barrier (with the opportunistic major slice in it), there are no more barriers and so we need to think through if it's safe for this to be run concurrently with another domain having re-entered the mutator (which may be filling it's minor heap with data again).

2023-02-09 10:47 UTC, sadiqj commented
On further pondering this could be fixed with: barrier -> finalisers -> final barrier with opportunistic work

(This also has the advantage that if there are finalisers which are long running, the other domains get to do some useful work hopefully)

2023-02-09 11:21 UTC, kayceesrk commented
It is not clear to me why we can process finalise_last finalisers while other domains may be running mutators. The minor heaps are empty at the end of minor collection. The domains only examine finalisers installed on their own minor heaps and no other domains will other domains' minor heap. What am I missing?

2023-02-10 09:43 UTC, sadiqj approved these changes
I looked through last night and this morning and agree with @kayceesrk , it should be safe to run the finalisers while other domains have returned to mutators and cleared their minor heaps (because a domain's young finalisers only point to their own minor heap).

2023-02-10 14:53 UTC, kayceesrk approved these changes
Please add a test to the testsuite.

2023-02-10 16:45 UTC, Engil commented
I pushed the test case (slightly modified to add a `full_major` call at the end to be sure the finaliser is indeed run).

However it does not currently pass the test suite, because it seems there's an inconsistency between the behaviour of the byte code and native version.

The byte code version does not seem to call the finaliser even if we call `full_major` before the end of the program, whereas the native one does.

Is this inconsistency expected, or is it another bug?

2023-02-11 06:52 UTC, kayceesrk commented
When something becomes unreachable may differ between native and bytecode.  

Can you try with this testcase?

```ocaml
let [@inline never] foo () =
  let s = "Hello" ^ " world!" in
  Gc.finalise_last (fun () -> print_endline "finalised") s;
  Gc.minor ();
  s

let [@inline never] bar () =
  let s = foo () in
  print_endline s

let _ =
  bar ();
  Gc.full_major ()
```

Here's what I see:

```
# with OCaml 5.0.0 ocamlc
finalised
Hello world!

# with OCaml 5.0.0 ocamlopt
finalised
Hello world!

# with this PR ocamlc
Hello world!
finalised

# with this PR ocamlopt
Hello world!
finalised
```

2023-02-13 12:13 UTC, abbysmal commented
This test case behave more consistently (regarding the byte code vs native difference.), Thank you very much!
I just pushed, I think this PR is ready for merging when it is greenlit.

2023-02-14 05:18 UTC, kayceesrk commented
`intext_par.ml` is failing on macOS. I went through the file and saw no references to finalisers. Can you confirm that this is indeed an orthogonal failure (and file an issue if this is the case)?

2023-02-15 07:36 UTC, kayceesrk commented
Given that the CI failure was unrelated to the changes here, I'm merging this PR.

2023-02-15 07:37 UTC, merged