documentation: Format.pp_print_newline wording
ocaml/ocaml pull request #12028
Opened 2023-02-22 13:45 UTC by Octachron

While reading the documentation of `Format.pp_print_newline`:

> Equivalent to {!print_flush}  followed by a new line.

@gasche and myself noted that the current wording does not guarantee that the new line emitted by the function is flushed at all.

This PR proposes to update this text to better reflect the implementation to:

>   Equivalent to {!print_flush} with a new line emitted on the pretty-printer
  low-level output device immediately before the device is flushed.

2023-02-22 13:49 UTC, gasche requested changes
I went to read format.ml to check your claim, and I would like to request a change that would make it more obvious: could you add a label to the boolean parameter of `pp_flush_queue`? (My tolerance for unlabelled boolean parameters is close to zero these days, I think we should label on sight.)

2023-02-22 13:55 UTC, gasche approved these changes
This looks fine now, thanks!

2023-02-22 13:55 UTC, gasche commented on Changes
> +  (Floian Angeletti, review by ????)
the ???? should be instantiated

2023-02-23 15:15 UTC, dra27 commented on Changes
> +  (Floian Angeletti, review by Gabriel Scherer)
```suggestion
  (Florian Angeletti, review by Gabriel Scherer)
```

2023-02-23 15:16 UTC, dra27 commented
Ready to squash-and-merge with CI

2023-02-23 16:28 UTC, merged