Clarifications to the "simple interface" part of the FFI manual chapter
ocaml/ocaml pull request #12402
Opened 2023-07-21 09:25 UTC by gasche

This is a follow-up to #12388:

- reword the paragraph introducing `CAMLreturn`, `CAMLreturn0` and `CAMLreturnT` to clarify that `CAMLreturn` should be used for exported primitives.
- start with an example of a simple exported primitive, before showing examples of helper functions
- add a `CAMLreturnT`  example in addition to `CAMLreturn0`
- move a mention of CAMLlocal that occurred before it was introduced in the text, and add an example of `CAMLparam0` that makes sense at the new location.

2023-07-22 09:27 UTC, yallop requested changes
This looks clearer overall.  I've noted some minor syntax issues

2023-07-22 09:27 UTC, yallop commented on manual/src/cmds/intf-c.etex
> +replace the C keyword "return"; any function using a `CAMLparam` macro
The use of <code>`</code> and <code>'</code> throughout this PR doesn't match the way quotations are used in the rest of the file.

2023-07-22 09:27 UTC, yallop commented on manual/src/cmds/intf-c.etex
> +`CAMLreturn0` -- and not have any implicit return. Helper functions
```suggestion
`CAMLreturn0`, and not have any implicit return. Helper functions
```

2023-07-22 13:53 UTC, gasche commented
Thanks @yallop! I had trouble switching from markdown to extended TeX, I fixed things according to your suggestions.

2023-07-25 09:54 UTC, yallop approved these changes

2023-07-25 10:39 UTC, stedolan approved these changes

2023-07-25 11:55 UTC, merged

2023-07-25 11:55 UTC, gasche commented
@Octachron I would be in favor of cherry-picking into 5.1, as well as the parent PR #12388, as an improvement to the manual. What do you think?

2023-08-01 08:54 UTC, Octachron commented
Done in 4cd480453d and c383cbde5.