Extending the representation attributes to allow Addr data
ocaml/ocaml pull request #1261
Opened 2017-07-24 14:01 UTC by ppedrot

Following [Mantis#7485](https://caml.inria.fr/mantis/view.php?id=7485), this PR extends the `[@@ocaml.immediate]` attribute with a generic `ocaml.repr(X)` attribute. In its current form, this new attribute can take the two following values:
- `immediate`, in which case it is equivalent to the old `ocaml.immediate` attribute;
- `address`, which means it is neither a float nor a lazy value (an `Addr` in Typeopt parlance).

This allows to ensure a few static optimizations by the compiler, e.g. regarding array accesses.

It provides a generic infrastructure for further extension of this mechanism to handle i.e. statically-known floats and whatnot. This has not been done yet as I don't know about all the potential optimization cases.

As requested per the contribution guidelines, I've added a few tests adapted from the immediate case. I did not add documentation yet, not knowing whether the attribute name and arguments would be accepted as-is. Also, I don't know what the guidelines are regarding bootstrap. This PR requires a bootstrap phase in the first two commits, but I find it a pity to store binary data in the repository, thus I didn't do it. I'd rather push a bootstrap commit when this PR is agreed on and before merge. Once again, correct me if that's wrong.

2017-07-24 14:05 UTC, alainfrisch commented
Ah, I had started to work on https://github.com/alainfrisch/ocaml/tree/keep_type_repr ;-)

2017-07-24 14:14 UTC, ppedrot commented
Aha, I had a look at your branch, and indeed this PR is probably wrong, as it doesn't care about the unboxed status of the types, which changes the representation... I should probably fix that, but I'm afraid I don't really understand everything that's going on here.

2017-07-24 14:22 UTC, alainfrisch commented
Well, my branch might be wrong as well.  It tries to keep the representation for each type declaration, in particular to merge various functions that currently approximate the representation.  But it doesn't actually do it properly, since this would involve recomputing the representation in particular after module substitution.  Consequently, the following is rejected:

````ocaml
module F(H: sig type t end) : sig type s = H.t end = struct type s = H.t end
module X = struct type t = int end
module Y : sig type t = int end = F(X)
````

(The signature inferred for X forgets the representation for X.t, but the expected signature implies "immediate".)

2017-07-24 14:35 UTC, lpw25 commented
Note that variance suffers from the same problem. I've previously thought that variance and immediacy should actually be computed lazily and then the lazy copies can be cleared by `Subst` -- basically the same as the `abbrev`s for type constructors.

2017-07-24 14:52 UTC, trefis requested changes
Mostly cosmetic changes :)

2017-07-24 14:52 UTC, trefis commented on testsuite/tests/typing-address/address.ml
> +       address is not a subrepresentation of any.
I find that error message pretty bad.

The "*of any*" part in particular feels terrible. I'd also avoid "*a subrepresentation of*" and use something like "*compatible with*" (although I guess this `repr` attribute is intended for "power users" who probably wouldn't be afraid when reading "subrepresentation").

Could we not produce more ad hoc and informative error messages for these errors?

2017-07-24 14:52 UTC, trefis commented on typing/ctype.ml
> -      (* if all labels are devoid of arguments, not a pointer *)
The code might be fairly straightforward, but I'm still sad that we're losing this comment.

In particular, I feel like this comment made it vaguely easier to understand why we're checking `row_closed`.

2017-07-24 14:52 UTC, trefis commented on typing/ctype.ml
> +      | _ -> true
I'm going to be super annoying, but I feel like this indentation style
- is not common in the codebase (you'll find it in parmatch, but not in many other places)
- is completely absent in this file.
- should be avoided (and I'm going to use the consistency fallacy to justify that)

You've used it in various places (it's probably some heritage of your coq background?) but I feel like the recommended style nowadays is something more like:
```ocaml
let foo x =
  match x with
  | Pattern ->
      code
  | Pattern' ->
      code
```

Do you mind changing that? :)

2017-07-24 14:52 UTC, trefis commented on typing/types.mli
> +    type_repr: type_repr;
I'm not familiar with the process so I don't know if you should do it in this PR, but some magic numbers will need to change as a consequence of this change.

2017-07-24 14:52 UTC, trefis commented on typing/typedecl.ml
>  let compute_immediacy env tdecl =
should this function not be renamed?

2017-07-24 14:52 UTC, trefis commented on typing/typedecl.ml
>        (fun (id, decl) (variance, immediacy) ->
please rename `immediacy` to `repr`

2017-07-24 14:52 UTC, trefis commented on typing/typedecl.ml
> +  | _ -> Repr_any
Couldn't this be `Repr_address` in some cases?
What about records whose fields are not floats?

Perhaps it just doesn't matter, but it's not obvious at quick glance that it doesn't.

2017-07-24 15:08 UTC, alainfrisch commented
Yes, actually, I'm "solving" the issue by following the manifest type when checking inclusion of representations.  This means that the type_representation field is really only useful on types without a manifest.

2017-07-25 20:35 UTC, gasche commented on typing/types.mli
> +    type_repr: type_repr;
We need to document this, I created an issue: to keep track: [MPR#7599](https://caml.inria.fr/mantis/view.php?id=7599).

2017-07-25 21:05 UTC, alainfrisch commented on testsuite/tests/typing-address/address.ml
> +module M_invalid : S = struct type t = float end;;
Why does this declaration succeed?  (Or perhaps I misinterpret the expect test.)

2017-07-25 21:56 UTC, alainfrisch commented on testsuite/tests/typing-address/address.ml
> +module M_valid : S = struct type t = T of int end;;
You should add an %%expect here, otherwise the two phrases are evaluated together and you get a single error.

2017-07-25 22:48 UTC, alainfrisch commented
Note that the most important optimization depend on knowing if the type is float or non-float: avoiding generic array accesses, allowing unboxing of unary existential constructors (`type s = A : 'a t -> s [@@unboxing]`).  Knowing that something is neither float nor lazy is "only" used to optimize expressions of the form `lazy x` (for some identifier `x`).

If we add to keep a single one, non-float seems more important to me than non-float-non-lazy, as it allows `type s = A : 'a t -> s [@@unboxing]` when `t` is implemented as `Lazy.t` and exposed as an abstract type marked as "non-float".  This can be definitely be useful.

Of course, one can keep both non-float and non-float-non-lazy ("address"), as the sister PR does.  That PR also support the "float" representation which might be useful in situations like:

````ocaml
module X : sig
  type t [@@float]
  type r = {x: t; y: t}
  val t_of_float: float -> t
end = struct
  type t = A of float [@@unboxed]  (* wrap in a constructor to locally enforce some invariants *)
  type r = {x: t; y: t}
  let t_of_float x =
    if x > 0. then A x else invalid_arg "..."
  ...
  (* here one cannot mix t and float by mistake *)
end
````

2018-05-14 11:43 UTC, ppedrot commented
Let me close this PR, as it is incomplete and has stalled. I don't have plans on working on it further.

2018-05-14 11:43 UTC, closed without merging