Generate runtime/prims.c with the correct types in primitive declarations
ocaml/ocaml pull request #12700
Opened 2023-10-30 10:15 UTC by xavierleroy

This is a resurrect of #11763 motivated by #12660.  In the generated prims.c file, we currently declare all primitives `caml_foo` as
```
extern value caml_foo(void);
```
which is not quite right.  This PR extracts the actual types of the primitives from their definitions, so as to generate the correct declaration with the right number and types of arguments.

Since I'm still not allowed to use a sensible scripting language for OCaml's build procedure, I tried hard to write simple, documented sed scripts, wrapped in a shell script, with comments.

While I was at it, I also simplified and cleaned up the generation of the runtime/primitives file (1st commit), and tweaked `floats.c` to rely less on macro magic and to be easier to scan (3rd commit).

2023-10-30 10:51 UTC, MisterDA requested changes
This looks good to me! I suggest also keeping the Dune build up to date with these changes (though it's broken at the moment, but for other reasons).
```diff
diff --git a/runtime/dune b/runtime/dune
index 9880c4fb4e..a22d72dfc8 100644
--- a/runtime/dune
+++ b/runtime/dune
@@ -13,7 +13,7 @@
 ;**************************************************************************

 (rule
- (targets primitives)
+ (targets primitives prims.c)
  (mode    fallback)
  (deps
    ; matches the line structure of files in gen_primitives.sh
@@ -25,8 +25,9 @@
      runtime_events.c sync.c
    dynlink.c backtrace_byt.c backtrace.c afl.c bigarray.c prng.c)
  (action
-   (chdir ..
-     (with-stdout-to %{targets} (run %{dep:gen_primitives.sh})))))
+   (progn
+     (with-stdout-to primitives (run %{dep:gen_primitives.sh} %{deps}))
+     (with-stdout-to prims.c (run %{dep:gen_primsc.sh} primitives %{deps})))))

 (rule
  (targets libcamlrun.a)
```

What about the generation of the primitives list in [bytecomp/symtable.ml](https://github.com/ocaml/ocaml/blob/80ca7e797b44f85e579feafec190e07183c78ed7/bytecomp/symtable.ml#L132-L178)? I assume there's nothing we can do here, since we don't have the typing information anymore?

2023-10-30 10:51 UTC, MisterDA commented on Makefile
> +                    runtime/primitives $(runtime_BYTECODE_C_SOURCES) \
```suggestion
                    $^ $(runtime_BYTECODE_C_SOURCES) \
```

2023-10-30 12:40 UTC, xavierleroy commented on Makefile
> +                    runtime/primitives $(runtime_BYTECODE_C_SOURCES) \
If you wish.

2023-10-30 12:46 UTC, xavierleroy commented
Thanks for the dune patch, applied.

> What about the generation of the primitives list in [bytecomp/symtable.ml](https://github.com/ocaml/ocaml/blob/80ca7e797b44f85e579feafec190e07183c78ed7/bytecomp/symtable.ml#L132-L178)? I assume there's nothing we can do here, since we don't have the typing information anymore

All we need is the arity of the primitive (number of arguments).  But I haven't looked into transmitting the arity (which is computed when ocamlc/ocamlopt process the external declaration) all the way to the bytecode linker.

2023-10-30 13:23 UTC, shindere commented
I very much like it that the list of files to scan for primitives now
comes from the Makefile rather than fromthe shell script, I even wonder
if the one in the script was complete. Are we sure we scan enough files
thouhg? Is it a property that the native runtime can't have primities
the bytecode runtime doesn't? I assume so but I don't mind asking a
stupid question.

2023-10-30 14:09 UTC, xavierleroy commented
> Are we sure we scan enough files thouhg? Is it a property that the native runtime can't have primities the bytecode runtime doesn't? 

The primitive table in runtime/prims.c is used exclusively by the bytecode interpreter, so it can only refer to primitives defined in the bytecode runtime.  If we were to include in runtime/primitives names of primitives defined exclusively in the native-code runtime system, the bytecode interpreter would fail to build.

2023-10-30 17:06 UTC, shindere commented
Xavier Leroy (2023/10/30 07:09 -0700):
> > Are we sure we scan enough files thouhg? Is it a property that the native runtime can't have primities the bytecode runtime doesn't?
>
> The primitive table in runtime/prims.c is used exclusively by the
> bytecode interpreter, so it can only refer to primitives defined in
> the bytecode runtime.  If we were to include in runtime/primitives
> names of primitives defined exclusively in the native-code runtime
> system, the bytecode interpreter would fail to build.

OK thanks for the clarification. Wouldthat perhaps deserve to be
documented? In theMakefile?

2023-10-30 17:10 UTC, MisterDA commented
I also would like to propose more changes to the Makefile.

1. Add the generating scripts as the first prerequisite. By using the `$^` (names of all the prerequisites, with spaces between them) variable, we can simplify the rules even further.
2. At the moment, we're always generating `runtime/primitives.new`, but we know its dependencies: `runtime/gen_primitives.sh` the generating script, and  `$(runtime_BYTECODE_C_SOURCES)` the list of sources containing primitives. We can extract it to a separate rule and avoid regenerating this file if the prerequisites haven't changed.

Applying these ideas gives https://github.com/MisterDA/ocaml/commit/a1cd61dc8dc1da6a884516e5e1ec9262ae9cf204.

2023-10-30 17:25 UTC, shindere commented
Antonin Décimo (2023/10/30 10:10 -0700):
> I also would like to propose more changes to the Makefile.
>
> 1. Add the generating scripts as the first prerequisite. By using the `$^` (names of all the prerequisites, with spaces between them) variable, we can simplify the rules even further.
> 2. At the moment, we're always generating `runtime/primitives.new`, but we know its dependencies: `runtime/gen_primitives.sh` the generating script, and  `$(runtime_BYTECODE_C_SOURCES)` the list of sources containing primitives. We can extract it to a separate rule and avoid regenerating this file if the prerequisites haven't changed.
>
> Applying these ideas gives https://github.com/MisterDA/ocaml/commit/a1cd61dc8dc1da6a884516e5e1ec9262ae9cf204.
>
I second these changes! :) Thanks a lot for your work and
investigation effort, @MisterDA.

2023-10-30 17:42 UTC, shindere commented
Re:dune I wanted to share the idea that we could add a phony target to the
Makefile to echo the list of source files of the runtime. That way we would
avoid duplicating it at the cast of Dune havingto invoke make but that price
looks worth it to me.

It's just that at the moment there is a cost associated with calling make,
because of the C dependencies and because it builds sak, I think, but I am
still sharing the idea in case either these costs feel acceptable or they
one day go away.

2023-10-30 17:48 UTC, xavierleroy commented
I agree with the extra dependencies on the C source files and on the script, but I'm really no big fan of the use of the `$^` notation to run the script and provide it with its arguments.  I prefer commands that I can read.

Re: the dune build, let's hear from people who actually use it.  It's been broken for quite a while and nobody seems to care.

2023-10-30 18:10 UTC, shindere commented
Xavier Leroy (2023/10/30 10:48 -0700):
> Re: the dune build, let's hear from people who actually use it.  It's
> been broken for quite a while and nobody seems to care.

Sure. I just wanted the idea to be in a public place for potential
future reference.

2023-10-30 20:40 UTC, gasche commented
The usual process with the dune build is to let people who don't care about it not care, and then be quick to merge PRs from people who are fixing it after the fact. (Basically, just trust them to change things as they want to and blindly merge, someone else can send a further PR if there was an issue.)

( @MisterDA next time I think you should send a separate PR for the dune changes. Bundling them in a PR is fine if the PR author cares about dune, but otherwise it just adds a bit of friction. )

2023-10-31 09:41 UTC, xavierleroy commented
> At the moment, we're always generating runtime/primitives.new, but we know its dependencies: runtime/gen_primitives.sh the generating script, and $(runtime_BYTECODE_C_SOURCES) the list of sources containing primitives. We can extract it to a separate rule and avoid regenerating this file if the prerequisites haven't changed.

This doesn't seem to work.  Try building the runtime system, then touch-ing one of the C files containing primitives.  You'll see that runtime/primitives is not rebuilt.  runtime/primitives.new is rebuilt if explicitly requested, but make doesn't consider it necessary.

2023-10-31 09:49 UTC, xavierleroy commented
I added Makefile dependencies on the runtime/gen*.sh scripts themselves.  I think that's about as much Makefile hacking I can tolerate in this PR.  Please don't ask for more Makefile hacking and finish the review of this PR.

2023-10-31 10:17 UTC, MisterDA commented
> > At the moment, we're always generating runtime/primitives.new, but we know its dependencies: runtime/gen_primitives.sh the generating script, and $(runtime_BYTECODE_C_SOURCES) the list of sources containing primitives. We can extract it to a separate rule and avoid regenerating this file if the prerequisites haven't changed.
> 
> This doesn't seem to work. Try building the runtime system, then touch-ing one of the C files containing primitives. You'll see that runtime/primitives is not rebuilt. runtime/primitives.new is rebuilt if explicitly requested, but make doesn't consider it necessary.

You're right, I don't know what happened during my testing of this yesterday. Thanks for trying, sorry for getting us into a false lead.

The PR works perfectly.

2023-10-31 10:36 UTC, gasche approved these changes
Approved on behalf of @MisterDA. I didn't look at this myself.

(@MisterDA: I am assuming that "The PR works perfectly" can be interpreted as you approving the idea of merging the PR. Next time, do not hesitate to explicitly "approve" the PR through the github UI, to reduce the guessing.)

2023-10-31 11:37 UTC, MisterDA approved these changes

2023-10-31 14:04 UTC, gasche commented
check-typo complains:

```
./runtime/gen_primsc.sh:65.1: [white-at-eof] empty line(s) at EOF
```

2023-10-31 15:14 UTC, xavierleroy commented
> check-typo complains:

Well spotted.  Fix under way.  Meanwhile, a poll:

Who is most annoying to OCaml developers?  1- the check-typo script, 2 - the stale bot.

2023-10-31 15:35 UTC, merged

2023-10-31 15:35 UTC, xavierleroy commented
Now merged.  Thanks @MisterDA and @gasche for the motivation and the feedback.