Propagate physical comparison operators to lambda
ocaml/ocaml pull request #13588
Opened 2024-11-02 19:48 UTC by hhugo

## Context 
The two snippets below currently compile to the same bytecode
 `let f (a : int) b = a = b`
 `let g a b = a == b`

In js_of_ocaml, I want to compile theses two differently. The reason is that the `===` javascript operator doesn't match the behavior of the standard ocaml runtime. 

For details, `-0. === 0.` returns `true` and `NaN === NaN` returns `false`. See https://github.com/ocsigen/js_of_ocaml/issues/1372

## This PR
This PR prepares the code base for the actual fix by forwarding more information to lambda.
This would allow https://github.com/ocaml/ocaml/pull/13438 to emit more hints or we could decide to change bytegen later to emit different code.

The main change in this PR is the addition of a primitive in lambda `Pphyscomp of physical_comparison`
and the following change in `translprim.ml` 
```diff
-    "%eq", Primitive ((Pintcomp Ceq), 2);
-    "%noteq", Primitive ((Pintcomp Cne), 2);
+    "%eq", Primitive ((Pphyscomp CPeq), 2);
+    "%noteq", Primitive ((Pphyscomp CPneq), 2);
```

2024-12-09 11:33 UTC, hhugo commented
@OlivierNicole, do you still plan to review this PR ?

2024-12-16 14:51 UTC, OlivierNicole commented
Sorry for the delay.

As this depends on #13438 to be useful, we should probably decide on the fate of that one first.

2026-03-25 15:56 UTC, OlivierNicole approved these changes
Overall this looks good to me modulo a small renaming suggestion in Instruct. This set of changes has the nice side effect that we will stop compiling `(==)` to `Pintcomp`, which I’ve always found a bit confusing.

2026-03-25 15:56 UTC, OlivierNicole commented on bytecomp/instruct.mli
> +  | Kintcomp of integer_comparison * bool
It would seem clearer to me to split this constructor in two on the model of Lambda, `Kintcomp of Lambda.integer_comparison` and `Kphyscomp of Lambda.physical_comparison`.

2026-03-25 15:56 UTC, OlivierNicole commented on bytecomp/instruct.mli
> +  | Hint_physical_comparison
```suggestion
  | Hint_physical_comparison
    (* Emitted from [(=)] or [(!=)] *)
```

2026-04-01 14:08 UTC, hhugo commented on bytecomp/instruct.mli
> +  | Kintcomp of integer_comparison * bool
I've done that in the last commit

2026-04-01 16:03 UTC, OlivierNicole commented on bytecomp/bytegen.ml
> +        (comp_primitive stack_info p (sz + nargs - 1) args :: cont)
```suggestion
(* Constant first for enabling further optimization (cf. emitcode.ml)  *)
  | Lprim (Pphyscomp _ as p, [arg ; (Lconst _ as k)], _) ->
      let args = [k ; arg] in
      let nargs = List.length args - 1 in
      comp_args stack_info env args sz
        (comp_primitive stack_info p (sz + nargs - 1) args :: cont)
```
The comment is misleading, there is no reason why `k` should be an integer (in the usual sense of the word integer).

2026-04-02 09:45 UTC, OlivierNicole requested changes

2026-04-02 12:43 UTC, OlivierNicole approved these changes
LGTM. Could you add a changelog entry?

2026-04-02 13:07 UTC, hhugo commented
> LGTM. Could you add a changelog entry?

done

2026-04-02 13:29 UTC, merged

2026-04-02 13:29 UTC, OlivierNicole commented
Thanks!