Stdlib: Mirror IO_BUFFER_SIZE and UNIX_BUFFER_SIZE in the stdlib and unix lib
ocaml/ocaml pull request #13589
Opened 2024-11-03 13:15 UTC by EruEri

#5938

Hi,

I tried to export those value to make it available in Ocaml, but I'm not sure whether the c functions are written in the appropriated files ?

2025-01-07 00:16 UTC, dbuenzli commented
Thanks @erueri for making the ball roll on that one. 

I have however one question for upstream. Is it really worth having separate constants for Unix and Sys ? 

Shouldn't we simply unify unix and sys to both use IO_BUFFER_SIZE and and simply expose `Sys.io_buffer_size` ?

2025-01-07 08:23 UTC, nojb reviewed
> I have however one question for upstream. Is it really worth having separate constants for Unix and Sys ?

If we believe that the existing API semantics of `Unix` are unlikely to change substantially in the future (which seems likely), then I guess we could do as suggested.

Incidentally, the constant `UNIX_BUFFER_SIZE` was initially introduced in d75dd36508169412b88e25276a841db3b940d061 and increase to its current value in 1ecb1f471cc23bd4b8cb085128763fe290c71eba. `IO_BUFFER_SIZE` was set to its current value in cf1071e8cad8a7abb41ea98fe43e6053667de019.

@damiendoligez: do you have an opinion?

2025-01-07 08:23 UTC, nojb commented on stdlib/sys.mli
> +*)
This docstring should be expanded. The whole point of this PR is to document an existing constant to avoid hard-coding values in user programs. Thus, I would expect that the docstring would explain which buffers are concerned, and how is this constant can be used in user programs.

2025-01-07 08:23 UTC, nojb commented on otherlibs/unix/read_win32.c
> +}
Since the constant is the same for both the Unix and Win32 backends, I would expect the definition of the function to be shared. However, I don't see right away a file where it could be put.

2025-01-10 07:56 UTC, EruEri commented on stdlib/sys.mli
> +*)
I honestly don't have a specific example to illustrate the use of those constants.
But like pointed out in the [issue](https://github.com/ocaml/ocaml/issues/5938), at least those values can be used in the stdlib instead of the hardcoded value.
https://github.com/ocaml/ocaml/blob/3fb2e4c9d2f25a5e052ae09c6eeafcded86a14c0/stdlib/in_channel.ml#L154

2025-01-27 14:45 UTC, OlivierNicole commented on stdlib/sys.mli
> +*)
What about “All channels are buffered by default. You may want to perform reads or writes of sizes equal to the buffer size to maximize throughput in certain situations, for instance.”

2025-02-08 09:17 UTC, nojb commented
> Shouldn't we simply unify unix and sys to both use IO_BUFFER_SIZE and and simply expose `Sys.io_buffer_size` ?

Let's do that. It has the advantage that we can always change our mind later and introduce `Unix.io_buffer_size` without breaking any code.

2025-02-08 09:46 UTC, nojb commented
@EruEri I took the liberty of rebasing the PR and implementing @dbuenzli's suggestion of merging `IO_BUFFER_SIZE` and `UNIX_BUFFER_SIZE`. I also added docstrings to the relevant functions in `Unix` indicating if they used an internal buffer and, if yes, its size.

At this point I think we need some reviews to move the PR forward.

2025-02-08 11:12 UTC, dbuenzli requested changes
The exposition of `Sys.io_buffer_size` looks fine to me. I'm a bit less convinced by the: 

```
No internal buffer is used.
```
and 
```
Uses an internal buffer of size {!Sys.io_buffer_size}.
```
comments which I find more confusing than enlightening. It also feels to me like an implementation detail. 

I think I would prefer to drop these comments in favor of a single, more involved, explanation in the doc string of `Sys.io_buffer_size`. Something like (en gros):

```
Size of C buffers used by the runtime system and [Unix] 
IO primitives to which OCaml [bytes] and [string]s are 
copied to/from to perform the IO operations without 
holding the domain lock.
```
Also it would be nice to use the new constant [here](https://github.com/ocaml/ocaml/blob/857b341b2a5fcadac14217ae694cd574637e6e94/stdlib/in_channel.ml#L154)

2025-02-08 11:45 UTC, nojb commented
> I think I would prefer to drop these comments in favor of a single, more involved, explanation in the doc string of `Sys.io_buffer_size`. Something like (en gros):

Thanks for the suggestion. I reworded it a bit; let me know what you think.

> Also it would be nice to use the new constant [here](https://github.com/ocaml/ocaml/blob/857b341b2a5fcadac14217ae694cd574637e6e94/stdlib/in_channel.ml#L154)

Done, thanks.

2025-02-08 12:05 UTC, dbuenzli approved these changes

2025-02-08 12:53 UTC, nojb commented
@EruEri I pushed a Changes entry for this PR. Please feel free to insert your real name (we do not normally use Github handles in the `Changes` file).

Other than that, this still needs one more approval by a core dev.

2025-02-08 12:54 UTC, gasche approved these changes
Approved on behalf of @dbuenzli. Thanks everyone for making progress on this decision-fatigue-generating issue.

2025-02-08 12:54 UTC, gasche commented on Changes
> +  (@EruEri and Nicolás Ojeda Bär, review by Daniel Bünzli and Nicolás Ojeda Bär)
For EruEri I suggest to use the full name Yves Ndiaye (as found in the commit email address), following our usual conventions.

2025-02-08 12:58 UTC, nojb commented on Changes
> +  (@EruEri and Nicolás Ojeda Bär, review by Daniel Bünzli and Nicolás Ojeda Bär)
Thanks, it's been amended (by @EruEri).

2025-02-08 13:00 UTC, EruEri commented
> @EruEri I pushed a Changes entry for this PR. Please feel free to insert your real name (we do not normally use Github handles in the `Changes` file).
> 
> Other than that, this still needs one more approval by a core dev.

Yes, it's done. Thanks you all of you for your time.

2025-02-08 16:30 UTC, merged