fix flexdll bootstrap
ocaml/ocaml pull request #1359
Opened 2017-09-20 12:42 UTC by damiendoligez

Make it possible to bootstrap `flexdll` on a machine that doesn't already have `ocamlopt` installed.

Remove a false sentence from `README.win32.adoc` (about flexlink.opt).

2017-09-22 17:04 UTC, alainfrisch commented
LGTM, but @dra27 implemented the flexdll bootstrap, so it'd be good to get his confirmation as well.

2017-09-25 12:46 UTC, dra27 requested changes
Docs change isn't quite right - using OCAML_CONFIG_FILE can only be a good thing, of course! I'm curious to know if this really wasn't working before (if it was, then pedantically, this is an improvement, not a fix :wink:)

2017-09-25 12:46 UTC, dra27 commented on README.win32.adoc
> -   `flexlink.exe` (i.e. there is never a `flexlink.opt.exe` installed).
Oops - I should have corrected this in #1145. It doesn't want deleting, though, it wants clarifying - s/opt.opt/flexlink.opt

2017-09-25 12:46 UTC, dra27 commented on Makefile
> +	           OCAML_CONFIG_FILE=../config/Makefile \
This is a sensible change, as it means the correct Makefile is read, but did you have an actual broken build? It was untidy, but when I originally did this, it was done so that the flexdll Makefile was passed all the variables it otherwise required from config/Makefile (I was also minimising changes to flexdll as well - `OCAML_CONFIG_FILE` I think first appears in flexdll 0.36?). My builds are routinely on machines with no installed ocamlopt, you just get these innocuous messages:

```
make -C flexdll \
             MSVC_DETECT=0 CHAINS=mingw64 NATDYNLINK=false support
make[1]: Entering directory '/cygdrive/c/Users/DRA/Documents/ocaml/flexdll'
make[1]: ocamlopt: Command not found
cygpath: cannot create short name of C:\cygwin\Makefile.config
/bin/sh: ocamlopt: command not found
for i in mingw64; do make build_$i; done
make[2]: Entering directory '/cygdrive/c/Users/DRA/Documents/ocaml/flexdll'
make[2]: ocamlopt: Command not found
cygpath: cannot create short name of C:\cygwin\Makefile.config
/bin/sh: ocamlopt: command not found
x86_64-w64-mingw32-gcc -c -DMINGW -o flexdll_mingw64.o flexdll.c
make[2]: Leaving directory '/cygdrive/c/Users/DRA/Documents/ocaml/flexdll'
make[1]: Leaving directory '/cygdrive/c/Users/DRA/Documents/ocaml/flexdll'
```

2017-09-25 12:46 UTC, dra27 commented on Makefile
>  	  TOOLPREF=$(TOOLPREF) CHAINS=$(FLEXDLL_CHAIN) NATDYNLINK=false \
`TOOLPREF` no longer needs to be passed, as flexdll/Makefile should get it via ../config/Makefile

2017-09-25 14:18 UTC, damiendoligez commented on README.win32.adoc
> -   `flexlink.exe` (i.e. there is never a `flexlink.opt.exe` installed).
Ah OK. When reading the Makefiles I'd missed the part that installs `flexlink.opt`.

2017-09-25 14:49 UTC, damiendoligez commented
@dra27 I'm not making these changes just for fun... Take a new machine, install Windows, cygwin, and VS2013, follow the instructions in `README.win32.adoc`, you get failure. Even ignoring the error messages is not enough.

I don't remember the exact error, but I had an error I don't see in your log: `test` was complaining that `-lt` was missing an argument because `OCAML_VERSION` ended up empty.

2017-09-25 14:53 UTC, damiendoligez commented
@dra27 I've done the changes you suggest.

2017-09-25 20:46 UTC, dra27 commented
Sorry - I didn't mean it flippantly, my confusion is that I have done what you describe countless times since it was added without hitting an error. The error you described you see with the flexdll 0.35 submodule, but again it should be innocuous:

```
make -C flexdll MSVC_DETECT=0 TOOLCHAIN=msvc \
  TOOLPREF= CHAINS=msvc64 NATDYNLINK=false \
  OCAMLOPT="../boot/ocamlrun ../boot/ocamlc -I ../boot" \
  flexlink.exe
make[1]: Entering directory '/cygdrive/d/build/ocaml/flexdll'
make[1]: ocamlopt: Command not found
cygpath: cannot create short name of C:\cygwin\Makefile.config
/bin/sh: ocamlopt: command not found
/bin/sh: line 0: [: -lt: unary operator expected
/bin/sh: line 0: [: -lt: unary operator expected
bash ./findwinsdk x86 > Makefile.winsdk
cygpath: can't convert empty path
bash ./findwinsdk x64 64 >> Makefile.winsdk
cygpath: can't convert empty path
make[1]: ocamlopt: Command not found
cygpath: cannot create short name of C:\cygwin\Makefile.config
/bin/sh: ocamlopt: command not found
/bin/sh: line 0: [: -lt: unary operator expected
/bin/sh: line 0: [: -lt: unary operator expected
echo "let version = \"0.35\"" > version.ml
echo "let mingw_prefix = \"i686-w64-mingw32-\"" >> version.ml
echo "let mingw64_prefix = \"x86_64-w64-mingw32-\"" >> version.ml
rm -f COMPILER-*
touch COMPILER-
cat COMPILER- > Compat.ml
rc version.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

Building flexlink.exe with TOOLCHAIN=msvc for OCaml
rm -f flexlink.exe
../boot/ocamlrun ../boot/ocamlc -I ../boot -o flexlink.exe -cclib "version.res" version.ml Compat.ml coff.ml cmdline.ml create_dll.ml reloc.ml
```
the strange messages to do with `test` were fixed in https://github.com/alainfrisch/flexdll/pull/24, but as it seemed to be cosmetic only, I didn't ask Alain to do an immediate release with that fix (it's in 0.36, of course).

So what's puzzling is what was broken before (and if your fix has wallpapered over something else which remains wrong).

2017-09-25 20:48 UTC, dra27 commented on Makefile
> +	           TOOLCHAIN=$(TOOLCHAIN) \
Sorry, I only reviewed this by the previous diff - good spot to remove `TOOLPREF` here too, but `TOOLCHAIN` can also go.

2017-09-26 13:55 UTC, damiendoligez commented
> and if your fix has wallpapered over something else which remains wrong

That's a good point. I'll try to diagnose precisely what was going wrong.

2017-10-04 12:57 UTC, damiendoligez commented
I tried (and tried) to reproduce the problem but I couldn't. This means that I was probably typing `make flexlink` instead of `make flexdll`, then I got sucked in by the error messages about "ocamlopt not found".

@dra27 I apologize for implicitly saying that your work was incorrect.

Now this PR is not needed except for the documentation part. Or do you think the Makefile part is really an improvement?

2017-10-04 13:47 UTC, dra27 commented
@damiendoligez - no problem, naturally! Now that we have to use flexdll 0.36+ for Unicode support, I see no reason not to incorporate this change (it's fundamentally neater) - it also means that if FlexDLL in the future happened to need another variable from config/Makefile then we wouldn't need to update our own build procedure to pass it through manually.

On the basis that any change is a risky change, possibly only put the Makefile alteration in trunk?

2017-10-05 12:18 UTC, damiendoligez commented
I generally tolerate more risk for build files because bugs usually lead to outright failures rather than hidden bugs. Moreover this is a fairly obscure part of the system, so even if it's buggy that won't inconvenience many people.

And I'd rather not deal with the added complexity of keeping two different versions of the patch.

2017-10-05 12:19 UTC, damiendoligez commented
@dra27 if you're satisfied with the current version of the patch, could you update your review?

2017-10-05 12:49 UTC, dra27 approved these changes

2017-10-05 12:49 UTC, dra27 commented
Done - sorry!

2017-10-05 14:48 UTC, merged

2017-10-05 14:50 UTC, damiendoligez commented
Cherry-picked [4.06 abd796e38b7dc7f8e378ed7f67e0a019567b8703]