Clarify Sys.executable_name behavior
ocaml/ocaml pull request #1395
Opened 2017-10-04 14:02 UTC by MiloDavis

We had a bug based on differences on the result of `Sys.executable_name` on OSX and Linux. The behavior also differs based on whether the program was compiled with `ocamlopt` and `ocamlc`. I'm using OCaml 4.04.2 in both locations.

Linux (Ubuntu 16.04.3):
```
ubuntu@ip-172-31-7-122:/tmp/executable-name$ cat test.ml
print_endline Sys.executable_name
ubuntu@ip-172-31-7-122:/tmp/executable-name$ ocamlc test.ml -o test
ubuntu@ip-172-31-7-122:/tmp/executable-name$ ./test
./test
ubuntu@ip-172-31-7-122:/tmp/executable-name$ ocamlopt test.ml -o test
ubuntu@ip-172-31-7-122:/tmp/executable-name$ ./test
/tmp/executable-name/test
```

OSX (Sierra 10.12.6):

```
~/Documents/ocaml/executable-name
$ ocamlc test.ml -o test

~/Documents/ocaml/executable-name
$ ./test
./test

~/Documents/ocaml/executable-name
$ ocamlopt test.ml -o test

~/Documents/ocaml/executable-name
$ ./test
./test
```

This PR updates the documentation to be explicit that this path may be relative or absolute.

2017-10-04 14:07 UTC, nojb commented
The behaviour of `ocamlopt` under Linux looks like a bug to me.

2017-10-04 14:16 UTC, nojb commented
Or rather the other way around, isn't `Sys.executable_name` supposed to give the full path?

2017-10-04 14:18 UTC, nojb commented
Also, on Windows, both `ocamlopt` and `ocamlc` prints the full path.

2017-10-04 14:20 UTC, nojb commented
Also #795 recently changed this part of the code.

2017-10-05 07:05 UTC, xavierleroy commented
There are several ways to determine a path to the executable file, depending on OS and context.  All behaviors shown above are correct.

2017-10-05 07:15 UTC, gasche commented
... and I think @nojb's reaction clearly demonstrates that people have different expectations and that more documentation cannot hurt.

Any change suggestion for the added comment? Personally I would suggest to add, in the list of things that the behavior depends on, "how the program is invoked".

2017-10-05 07:16 UTC, gasche approved these changes

2017-10-08 13:55 UTC, xavierleroy commented
It's not clear that "The path" on line 2 refers to the same thing as "The file" on line 1.  

The OCaml docs talk about "file names" and use "path" mostly for search paths.

The POSIX docs use "pathname".

I'd rather say "The name" or if you must "The path name".

Also, "relative" -> "relative to the current working directory".

2017-10-10 14:03 UTC, damiendoligez commented
I would write "This name" instead of "The path" on line 2.

2017-10-10 14:04 UTC, damiendoligez requested changes

2017-10-10 14:04 UTC, damiendoligez commented on stdlib/sys.mli
> +    The path may be relative or absolute depending on the platform and
Suggested edit:
`This name may be absolute or relative to the current directory, depending on...`

2018-02-28 14:11 UTC, merged