Improved documentation of unboxed and noalloc attributes
ocaml/ocaml pull request #1422
Opened 2017-10-09 19:20 UTC by mmottl

It is easy to miss the note at the top of the manual section `19.10  Advanced topic: cheaper C call` that it only applies to the native code compiler.  This patch improves the wording of subsections to make this more evident to readers who jumped there directly.

This patch fixes [MPR#7655](https://caml.inria.fr/mantis/view.php?id=7655).

2017-10-10 17:15 UTC, Octachron requested changes
I like the idea of helping readers that jumped directly into the midst of the section. Thanks for the PR! However, for the sake of consistency in this chapter of the manual, the `native code` compiler spelling should be fixed. On a more minor level, there are a lot of noise in the commit diff due to unrelated words and spaces moving around; it may be nice to fix this point.

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +"value", and one has to use macros such as "Int_val" to decode data from
Why move `from` here from the line below?

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +the "value" type.  It is however possible to tell the OCaml native code
`native code` ⇒`native-code` : this chapter uses consistently the `native-code` spelling.

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +The motivation is that, by letting the OCaml native code compiler deal with
`native code` ⇒`native-code` .

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +Now if we annotate the arguments and result with "[\@unboxed]", the native
One more `native code` ⇒`native-code`

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +In order to be able to run the garbage collector in the middle of
Why add a linebreak here?

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +code around C calls.  Technically it wraps every C call with the C function
The double space is unneeded here.

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +the C function doesn't allocate and doesn't raise exceptions.  We can
Why changes any of the lines above in this paragraph?

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +instruct the OCaml native code compiler of this fact by annotating the
`native code` ⇒`native-code`

2017-10-10 17:15 UTC, Octachron commented on manual/manual/cmds/intf-c.etex
> +Similarly it is possible to tell OCaml to expect the result unboxed and box
If you want to avoid the OCaml native-code compiler repetition, you could use `ocamlopt` rather than `OCaml` .

2017-10-10 18:52 UTC, mmottl commented
It seems that the manual (even this chapter) is not particularly consistent wrt. the spelling of "native code" and "native-code".  I've even seen "native compiler".  Obviously, I don't care either way and don't even mind the inconsistency as long as explanations are clear.

Concerning the formatting, it seems the raw text was formatted to fit within at most 80 (sometimes even 75) characters per line.  That's why I had to reformat some paragraphs to stay within bounds.  Automatic formatting usually introduces an extra space after sentences to help editors jump over dots with different meaning (e.g., etc., i.e.) when navigating sentences.  Latex generally ignores extra whitespace anyway.

My personal preference is to keep the formatting rather than reduce the diff size, but it's not important in either case for me.

Let me know how important preserving the formatting is, even if the changes exceeded text bounds, and I'll fix that besides the "native-code" change.

2017-10-11 10:24 UTC, Octachron commented
The formatting changes are fine by themselves, it just made it harder for me to locate the meaningful changes when reviewing.

2017-10-11 13:18 UTC, damiendoligez commented
The 80 character limit is more important than the diff size.

2017-10-11 16:26 UTC, mmottl commented
I usually use [Patdiff](https://github.com/janestreet/patdiff) for diffing, which can be integrated with `git` by adding the following to `.gitconfig`:

```
[alias]
  pdiff = !sh -c 'cd ${GIT_PREFIX:-.} && git difftool -y -x patdiff $* | less' -
```

It can handle whitespace (including wrapped lines) flexibly and use colored output, which typically makes diffs much shorter and easier to read for these kinds of changes.

I've kept the 80 character limit as before and made the spelling of `native-code` consistent in this section.

2017-10-12 11:49 UTC, Octachron approved these changes

2017-10-12 11:49 UTC, Octachron commented
Thanks for the `native-code` change.

2017-10-12 15:44 UTC, merged

2017-10-12 15:47 UTC, gasche commented
Merged, cherry-picked in 4.06 ( 10c0fbf7afb73d1dd212a0c320a13260ba749f8a ).