Add a padding word before "data_end" symbols (MPR#6329)
ocaml/ocaml pull request #1437
Opened 2017-10-20 08:56 UTC by mshinwell

I think this will fix MPR#6329 by ensuring that if the page table is tested for the address of an empty block immediately before a "data_end" symbol, then there will be a valid result.  The Mantis issue contains the full details of the problem.  I don't believe I have any way of reasonably testing this; the reproduction case involved a binary.

2017-10-20 17:17 UTC, xavierleroy requested changes
Looks good except for the ARM64 emitter.

2017-10-20 17:17 UTC, xavierleroy commented on asmcomp/arm64/emit.mlp
>    `	.globl	{emit_symbol lbl_end}\n`;
Should be `.quad` I believe.

2017-10-23 09:22 UTC, mshinwell commented on asmcomp/arm64/emit.mlp
>    `	.globl	{emit_symbol lbl_end}\n`;
Goodness, yes.  Fixed.

2017-10-23 12:24 UTC, xavierleroy approved these changes
Looks good.  I gave this branch a round of "precheck" at Inria's CI and it builds and tests fine on all the target architectures.  

What I am unsure about is whether this should go in 4.06.  It's very late in the release cycle for an extremely rare bug.  I'll let @damiendoligez and @gasche decide.

2017-10-23 12:38 UTC, gasche commented
Given the testing that was done, what would be the potential impact of an unforeseen issue with this patch?

2017-10-23 14:20 UTC, xavierleroy commented
Well, after two betas and one week (?) before a release, you don't change the compiler unless you run into a show-stopper bug, no matter how innocuous the fix looks like.  If you're planning more betas and a delayed release, perhaps.

2017-10-23 14:33 UTC, gasche commented
Well let's go for trunk-only then :-)

2017-10-23 14:34 UTC, gasche commented
We need someone to move the Changes entry back to trunk territory then, and then merge.

2017-10-23 15:04 UTC, mshinwell commented
Does this mean all other GPRs which fix (non-showstopper) bugs in 4.06 are now moved to 4.07?

2017-10-23 15:19 UTC, xavierleroy commented
That would be a question for caml-devel, I think.  My personal feeling: patches to non-critical parts of the distribution (e.g. the test suite, the manual) can still be accepted in 4.06 for a few more days, but not changes to the runtime system and the compilers.

2017-10-24 15:57 UTC, merged

2017-10-24 15:58 UTC, mshinwell commented
Merged to trunk and cherry-picked to 4.06 as per approval on email of @damiendoligez .