Organise and simplify translation of primitives
ocaml/ocaml pull request #1557
Opened 2018-01-03 15:46 UTC by lpw25

Currently the translation of builtin `external`s in bytecomp is pretty disorganized. It is handled across multiple parts of `translcore.ml` and different builtins are handled in different places. This has lead to a number of silly little bugs, e.g. [this one](https://caml.inria.fr/mantis/view.php?id=7666) or this bug that is still on trunk:
```ocaml
# module M : sig
    val send : CamlinternalOO.obj -> CamlinternalOO.tag -> CamlinternalOO.t
  end = CamlinternalOO ;;
    Characters -1--1:
  module M : sig
  
Error: The external function `%send' is not available
```

This PR tries to improve the situation. It moves all the handling for primitives into a new `translprim.ml` file, and uses an internal type:
```ocaml
type prim =
  | Primitive of Lambda.primitive
  | Comparison of comparison * comparison_kind
  | Raise of Lambda.raise_kind
  | Raise_with_backtrace
  | Lazy_force
  | Loc of loc_kind
  | Send
  | Send_self
  | Send_cache
```
to represent the various builtin `external`s. The cases other than `Primitive` are the ones that require special handling. These have previously been handled in different ad-hoc ways but here are handled by a fairly uniform set of functions in `translprim.ml`.

2018-01-03 15:58 UTC, gasche commented
That sounds like an excellent idea to me, although I still have to look at what you have done.

cc @bobot @nojb, who have been working on #1465

2018-01-03 16:48 UTC, xclerc commented
I am unsure whether it should be done in this PR, but some cases of
`Semantics_of_primitives.for_primitive` seem to be wrong.
For instance, `caml_format_{float,int}`/`caml_{int32,int64,nativeint}_fomat`
do allocate. Similarly, reading from a big array might allocate, depending on
its kind.

2018-04-02 16:56 UTC, hhugo commented
@damiendoligez, can we consider this one for 4.07 or at least merge https://github.com/ocaml/ocaml/pull/1465

2018-04-06 20:13 UTC, hhugo commented
@damiendoligez, @lpw25, can we have this PR in 4.07 ?

2018-04-07 08:17 UTC, nojb commented
I have been studying this PR and will post a review at some point today.

2018-04-07 14:04 UTC, nojb requested changes
I reviewed this PR.

I think it is a great improvement on the current state of affairs. I read the code carefully and am confident it is correct (modulo a small issue with the handling of the `raise` primitive). More importantly, I am confident that **if** there is a bug, it will be easy to find and fix thanks to the new code organization. This is in contrast with the current state of affairs where the handling of primitives is spread all over the place and many invariants are not tracked by the type system.

Some remarks about the code itself.

While the diff is large, a lot of it is due to moving code around and "type-directed" refactoring.

Conceptually, the PR does several things:

  - merge the code used by `transl_primitive` (which eta-expands a primitive) and `transl_primitive_application` (which translates a fully applied primitive). This cuts down on a lot of duplicated code, and fixes at least [MPR#7674](https://caml.inria.fr/mantis/view.php?id=7674) and [MPR#7666](https://caml.inria.fr/mantis/view.php?id=7666).
  - A more robust function to lookup primitives `lookup_primitive` instead of `find_primitive`. This would have produced a sensible error message for [MPR#7666](https://caml.inria.fr/mantis/view.php?id=7666).
  - Clean up the insertion of debug events in the generated lambda code (functions `wrap` and `wrap0`). The current code here is so convoluted that it took me some time to convince myself that the new code (which is simpler) is actually equivalent.
  - Introduce a new type `Translprim.prim` which includes the usual `Lambda.primitive` but also other primitives that do not currently have a representation in the type system and are only recognized by their names. The "new" primitives are: comparison primitives, `send`, `sendself`, `sendcache`, and `raise_with_backtrace`. Having constructors corresponding to these primitives allows to use pattern matching and, in the case of comparisons, to handle them before specialization.
  - Some primitives that need special handling are lifted out of the `Lambda.primitive` type into the new `Translprim.prim` type. On the one hand pattern matching makes it obvious where special handling is needed. On the other hand, it also makes it clear that these primitives do not survive lambda-generation. The primitives affected are: `raise`, `lazyforce`, and `loc_*` primitives.

In an ideal world, having the PR split into smaller commits would make it easier to digest, but personally I don't feel it is reason enough to delay its integration.

2018-04-07 14:04 UTC, nojb commented on bytecomp/translprim.ml
> +let lamda_of_loc kind loc =
s/lamda/lambda/

2018-04-07 14:04 UTC, nojb commented on bytecomp/translprim.ml
> +    match specialize_primitive env ty ~has_constant_constructor prim with
Why not have `specialize_primitive` return `prim` instead of `prim option`?

2018-04-07 14:04 UTC, nojb commented on bytecomp/translprim.ml
> +            Raise_regular
Should probably be `kind` instead of `Raise_regular`, to avoid changing `Raise_notrace` case.

2018-04-09 11:22 UTC, lpw25 commented on bytecomp/translprim.ml
> +    match specialize_primitive env ty ~has_constant_constructor prim with
It is needed for implementing https://github.com/ocaml/ocaml/pull/1566.

2018-04-09 12:03 UTC, lpw25 commented
I've rebased, addressed comments and added a changes entry.

2018-04-09 12:03 UTC, lpw25 commented on bytecomp/translprim.ml
> +let lamda_of_loc kind loc =
fixed

2018-04-09 12:03 UTC, lpw25 commented on bytecomp/translprim.ml
> +            Raise_regular
Good catch. Fixed.

2018-04-09 12:04 UTC, lpw25 commented on bytecomp/translprim.ml
> +(* Insertion of debugging events *)
I don't think there is documentation, nor to I know the rules and invariants. I tried simplifying things when writing this patch, but it made some tests around backtraces fail, so instead I was just careful to keep the behaviour the same.

2018-04-09 12:05 UTC, nojb approved these changes

2018-04-09 12:06 UTC, lpw25 commented on bytecomp/translprim.ml
> +
I decided against adding a comment. I don't think it makes adding a new primitive noticeably easier and these kinds of comments tend not to get updated when things change, leaving things in a worse state than if they weren't there.

2018-04-09 12:06 UTC, lpw25 commented on bytecomp/translprim.ml
> +      raise(Error(loc, Wrong_arity_builtin_primitive prim_name))
Fixed.

2018-04-09 12:48 UTC, lpw25 commented
The CI failure is unrelated to this patch (and has now been fixed on trunk).

2018-04-09 12:50 UTC, merged

2018-04-09 13:19 UTC, shindere commented
Inria's CI fails on ARM.
File "translprim.mli", line 18, characters 19-39:
Error: Unbound module Typedtree

Is this just a matter of running make alldepend?

2018-04-09 13:33 UTC, lpw25 commented
I ran `make depend`, and I can see the line:

>  bytecomp/translprim.cmi : typing/types.cmi typing/typedtree.cmi

in the commits, so this is a surprising error.

2018-04-09 13:46 UTC, lpw25 commented
Ah, there is aparently now a `ocamldoc/stdlib_non_prefixed/.depend` file that also needs updating, and gets updated by `make alldepend`. Mark has pushed the fix to trunk.

2018-04-09 13:52 UTC, shindere commented
Leo White (2018/04/09 13:46 +0000):
> Ah, there is aparently now a `ocamldoc/stdlib_non_prefixed/.depend`
> file that also needs updating, and gets updated by `make alldepend`.
> Mark has pushed the fix to trunk.

Thanks guys!

2018-04-09 15:10 UTC, hhugo commented
Thanks