[WIP] Compilers without support for flat float arrays
ocaml/ocaml pull request #1589
Opened 2018-01-30 11:14 UTC by xclerc

(This comment is *very* long, in an attempt to cover/discuss all cases.)

There seems to be various problems regarding the interaction between
distributions built with and without support for flat float arrays (FFA below).
These problems have a common root that is the production / expectation
regarding blocks with tag 254:

- a program/compiler with support for FFA will produce values with tag
  254 for the `float array`, `floatarray` and all-float record types;
- a program/compiler without support for FFA will expect values with tag
  254 only for `floatarray` and all-float record types, and will expect values
  with tag 0 for the `float array` type.

A program expecting a block with tag 0 but actually getting a block with tag
254 is more than likely to segfault at some point.

The current PR addresses various occurrences of this issue.

### Mixing modules

It is possible to produce a program that segfaults by compiling a module
with the following signature with a compiler with support for FFA:

    val f : ... -> float array

and then use it from a module compiled without support for FFA:

    let () = Array.iter print_float (Aux.f ...)

This can be fixed by adding a new flag to `cmi` files (akin to the flag for
unsafe strings) in order to avoid mixing modules. See commit 92d483ab.

(For this to work properly, it needs the bytecode compiler in the `boot/`
directory to be compiled without support for flat float array. This is checked
by the travis script. See commits 8444618e and b03f3d84.)

### Bytecode executables

A bytecode executable produced by a compiler with support for FFA can
segfault if executed with an `ocamlrun` VM compiled without support for FFA
if it contains a `MAKEFLOATBLOCK` instruction generated for a value of type
`float array`. For instance:

    let a = [| 0.; 1.; 2. |]
    let () = Array.iter print_float a

(Note that if this snippet is added to the code of the compiler, *e.g.* in
`driver/main.ml`, a segfault will occur while trying to build a distribution
configured with `-no-flat-float-array`.)

This is currently documented on the manual page for `ocamlrun`. See commit
ec17a4d1.

Another option would be to bump the magic number for bytecode executables,
and store the information about FFA support, refusing to execute a file if a
segfault might occur.

*Actual* fixes are also possible, depending on whether it is deemed important
to provide backward compatibility. For instance, some key array-related
primitives might keep their original semantics (*i.e.* include a dynamic check
for the kind of array) only for bytecode compilation. It is trivial for get/set/length
primitives but is slightly more complex for blit/gather (because these ones
currently assume that the various arrays involved in a given operation have the
same layout).

### Marshaling in user code

If a program compiled with support for FFA marshals a value of type `float array`
then unmarshaled by a program compiled without support for FFA, array uses
can segfault.

This is documented in the ocamldoc comment of the `Marshal` module.
See commit 9e5e2015.

### Marshaling in compiler code, dynamic linking

While this is not currently the case, a compiler might marshal `float array`
values to `cm`*K* files. Then unmarshaling such values might cause segfaults.

This can be avoided by adding a boolean indicating whether the file might
contain flat arrays to all `cm`*K* files. The boolean is also used to ensure
that a program compiled without support for FFA does not try to dynamically
load files compiled with support for FFA. See commit a817ad8c.

### TODO

This PR is still a work in progress; still pending:

- update the sources in `tools/`;
- (possibly) rewrite some changes above as they are are partially redundant;
- (possibly) add a way for the user to directly access to the information about
  FFA support (*e.g.* in the `Sys` module), native dynlink currently uses
  `Obj.(tag @@ repr [| 0. |] = double_array_tag)`;
- update chapter 20 ("Interfacing C with OCaml") of the manual;
- make sure that the various CI instances build variants without FFA support;
- create opam switches without FFA support to encourage testing.

2018-02-08 10:38 UTC, xclerc commented
The changes above are not sufficient, as shown by the Travis failure
of the flambda variant. Indeed, an flambda compiler built using a
boostraping compiler without FFA support but run with an `ocamlrun`
with FFA support will fail, because the flambda compiler builds value
of type `float array`.

One solution is to avoid the construction of value with type `float array`,
(see commit `c668190e`) but it is brittle at best, because such values are
intermediary results (*e.g.* `Array.map (fun x -> Some x) (Array.of_list fs)`
with `fs` a list of `float` value in file `asmcomp/export_info.ml`).

Other solutions include:
- having the primitive retain their "old" semantics when in bytecode mode;
- restore the "old" semantics of array primitives and introduce new
  primitives, to be used ` in 4.07+.

2018-03-29 15:03 UTC, damiendoligez commented
I have a few remarks:

* It's nice to detect and prevent the mixing of files from differently-configured compilers.
* Cross-compatibility is not a goal, performance is. If you reintroduce run-time checks in the primitives, that defeats the whole purpose of the configure option. (re: your "other solutions")
* The only place where I'm interested in cross-compatibility is making the bootstrap easier or faster.
* I'm worried about the dissymetry of your code: you refuse FFA-marshalled values in no-FFA programs, but you accept the reverse. This is probably OK as long as you stay in OCaml, but any (user-defined) C primitive that deals with `float array` will crash or even return buggy results. I'll be more at ease if you just forbid mixing the two configurations altogether.

2018-03-29 15:17 UTC, xclerc commented
> I'm worried about the dissymetry of your code: you refuse FFA-marshalled values in no-FFA programs, but you accept the reverse. This is probably OK as long as you stay in OCaml, but any (user-defined) C primitive that deals with float array will crash or even return buggy results. I'll be more at ease if you just forbid mixing the two configurations altogether.

I understand your point, but there is currently only one boostrap directory
that is used whatever the user pass to the configure script. Do you suggest
to have two bootstrap directories?

2018-03-29 15:31 UTC, xclerc commented
> any (user-defined) C primitive that deals with float array will crash or even return buggy results

I would expect the primitive to behave according to the value of `FLAT_FLOAT_ARRAY`
in `${PREFIX}/lib/ocaml/Makefile.config`.

2018-03-30 14:14 UTC, damiendoligez commented
> Do you suggest to have two bootstrap directories?

Ouch, no. I'll keep your not-completely-safe solution rather than duplicate the bootstrap binaries.

> I would expect the primitive to behave according to the value of `FLAT_FLOAT_ARRAY`
in `${PREFIX}/lib/ocaml/Makefile.config`.

Yes, so your FFA-configured program accepts a no-FFA marshalled value and crashes. I guess we'll have to live with that.

2018-07-24 10:06 UTC, xclerc commented
Would it make sense to use the marshaling header (or magic number)
to detect incompatibilities to could lead to a segfault?

2018-10-12 13:30 UTC, damiendoligez commented
I think the best solution is to change the magic number of mashaled files. You don't have room in the header for the FFA information.

2018-10-12 14:08 UTC, damiendoligez requested changes
Looks good in general. Just a few requests.

2018-10-12 14:08 UTC, damiendoligez commented on middle_end/allocated_const.mli
> +  (* CR-someday mshinwell: consider using "float array" (or "floatarray") *)
You should keep only the `"floatarray"` option : it will generate less trouble because it is compatible across configurations.

2018-10-12 14:08 UTC, damiendoligez commented on otherlibs/dynlink/dynlink.ml
> +    "implementation mismatch on " ^ name
inconsistent indentation on this line

2018-10-12 14:08 UTC, damiendoligez commented on stdlib/sys.mli
> +    @since 4.07.0 *)
you need to update this tag :-(

2018-10-12 14:08 UTC, damiendoligez commented on tools/objinfo.ml
> +  let check_float_float_arrays has_float_arrays =
This should be `check_flat_float_arrays`, right?

2018-10-12 14:08 UTC, damiendoligez commented on tools/objinfo.ml
> +    end;
This strange conditional should be replaced with a call to `check_flat_float_arrays`.

2018-10-12 14:08 UTC, damiendoligez commented on utils/config.mlp
> +and cma_magic_number = "Caml1999A023"
Don't update the magic numbers in the PR, the policy is to bump them just before releasing the first beta of a major version.

2018-11-09 13:37 UTC, xclerc commented on tools/objinfo.ml
> +  let check_float_float_arrays has_float_arrays =
Indeed.

2018-11-16 12:54 UTC, damiendoligez commented
> Would it make sense to use the marshaling header (or magic number)
to detect incompatibilities to could lead to a segfault?

Yes, it would!

2021-04-28 12:30 UTC, gasche commented
What is the status of this PR? Is there still interest in working on this? (There was an issue with the rebase apparaently, which should be re-done to keep a clean patchset.)

2023-03-10 12:43 UTC, closed without merging

2023-03-10 12:44 UTC, damiendoligez commented
@xclerc feel free to reopen if/when you want to resume work on this.