Make updating lex_curr_p/lex_start_p optional
ocaml/ocaml pull request #1590
Opened 2018-01-30 16:44 UTC by alainfrisch

Follow up to #1585, where I noticed that disabled the update of lex_curr_p/lex_start_p can bring significant speedup to lexers generated by ocamllex.  Since #1585, lexers generated by "ocamllex -ml" don't update these fields if `lex_curr_p == Lexing.dummy_pos` (the lexer actions need to be careful not to break this property).

This PR document this behavior, and port it to lexers generated by ocamllex (without -ml).

2018-05-11 10:56 UTC, alainfrisch commented
@let-def : do you have an opinion on this small change?

2018-05-16 15:40 UTC, diml commented
Personally I find the motivation valid, but the API a bit error prone. For instance if some code outside of lexing.ml modifies `lex_curr_p` without comparing it to `Lexing.dummy_pos`, then the results are going to be random.

Couldn't we arrange things so that when updating `lex_curr_p` and `lex_start_p` is disabled, these fields have type `unit`?

2018-05-16 16:07 UTC, alainfrisch commented
> Couldn't we arrange things so that when updating lex_curr_p and lex_start_p is disabled, these fields have type unit?

I don't really see precisely how to do that, and even if it were possible, this would prevent using the same code in different contexts where the locations need to be updated or not.  With the current API and the proposed PR, if the lexer is properly written (so as not to update lex_curr_p/lex_start_p manually without checking for dummy first), it can be used in the two modes; the caller decides if locations need to be tracked or not.  This allows in particular running a parser first without collecting locations, and running it again collecting location in case an error needs to be reported.

2018-05-16 16:20 UTC, ghost commented
I suppose it could be done with a GADT:

```ocaml
type 'a lexbuf_kind =
  | With_positions : position lexbuf_kind
  | Without_positions : unit lexbuf_kind

type _ generic_lexbuf =
  { lex_kind : 'a lexbuf_kind
  ; mutable lex_curr_p : 'a
  ; ...
  }

type lexbuf = position generic_lexbuf
```

then lexers that have been updated to support both modes would take a `generic_lexbuf`.

2018-05-16 17:09 UTC, alainfrisch commented
With the current API, the worst thing that can happen is that people fail to benefit from the optimization if they are not careful about how they write their code.  I don't think this justifies the added complexity of the API you suggest.

> For instance if some code outside of lexing.ml modifies lex_curr_p without comparing it to Lexing.dummy_pos, then the results are going to be random.

Well, such code would already behave in a weird way if the lexer keeps its initial dummy_pos fields (with cnum = -1, for instance).

2018-05-17 07:49 UTC, diml commented
Hmm, I'm still not fully convinced, but I'm OK with this implementation if we can make the API express the intent a bit better. At least to make it easier to understand what the programmer had in mind when reading code using this feature.

For instance, we can add an argument `?update_positions:bool` to the creation functions and a new function `should_update_positions : lexbuf -> bool`. IMO, the physical equality check shouldn't be documented and left as an implementation detail.

2018-05-29 09:59 UTC, damiendoligez commented
Note that this should be ported to 4.07 to avoid a discrepancy between the two modes of `ocamllex`.

@alainfrisch @diml can we converge quickly?

2018-05-29 11:18 UTC, alainfrisch commented
> For instance, we can add an argument ?update_positions:bool to the creation functions and a new function should_update_positions : lexbuf -> bool

Do you suggest (1) extending the lexbuf record with an extra field, or just (2) having `should_update_positions` defined as `fun buf -> buf.lex_curr_p != dummy_pos`?

I'm happy with (2), but it does not seem compatible with the idea of adding the `?update_positions:bool` argument to creation functions.

2018-05-29 11:19 UTC, alainfrisch commented
> Note that this should be ported to 4.07 to avoid a discrepancy between the two modes of ocamllex.

I think it's only a performance discrepancy (except for people who rely on dummy_pos being updated, but this would seem a bit crazy).

2018-05-30 08:42 UTC, diml commented
I suggest (2). I think it's compatible with adding the `?update_positions:bool` argument: `lex_curr_p` would be initialised as follow in `lexing.ml`:

```ocaml
lex_curr_p = if update_positions then zero_pos else dummy_pos
```

The idea is that if one sees `lexbuf.lex_curr_p <- Lexing.dummy_pos` in user code, it's not really clear why the code is doing this. On the other hand it's quite clear what `Lexing.from_string s ~update_positions:false` is expected to do.

2018-05-30 22:16 UTC, alainfrisch commented
Ah right, sorry, I forgot that functions building lexbufs were using zero_pos, not dummy_pos.  I like your proposal, now!   Just wondering about the risk of changing the API for 4.07.  The extra optional argument could break some code; the risk is small, but do we want to take it so close from a release?

2018-05-31 07:29 UTC, alainfrisch commented
@diml : I've implemented your proposal, with slightly different names.  Are you ok with the names, and the documentation?  

I've left the Changes entry in the 4.07 section in order to simplify cherry-picking if we decide to have this in 4.07.

2018-05-31 07:47 UTC, gasche commented
I think that this is a nice change, but I don't feel a particular urgency to get it into 4.07 rather than trunk.

2018-05-31 13:34 UTC, ghost approved these changes

2018-05-31 13:34 UTC, diml commented on stdlib/lexing.mli
> +   create lexer buffer. In this mode, the lexing engine and lexer
this should be plural: buffers*

2018-05-31 13:34 UTC, diml commented on stdlib/lexing.mli
> +    [lex_curr_p] / [lex_start_p], as determined by the correspond
corresponding*

2018-05-31 13:34 UTC, diml commented on stdlib/lexing.mli
> +    optional argument for function that create lexer buffers
functions*

2018-05-31 13:35 UTC, ghost requested changes
I ticked the wrong box...

2018-05-31 13:36 UTC, diml commented
@alainfrisch, yes, they look good to me

2018-05-31 14:51 UTC, alainfrisch commented
Typos fixed. Changes entry fixed and moved to "Working version".

@diml  If you agree not to include that in 4.07, can you approve and possibly merge this PR (I'd use "Squash and merge")?

2018-05-31 16:11 UTC, ghost approved these changes

2018-05-31 16:12 UTC, merged

2018-05-31 16:12 UTC, diml commented
Sure, done