Do not allow recursive modules in `with module`
ocaml/ocaml pull request #1626
Opened 2018-02-21 10:58 UTC by lpw25

Currently, recursive modules can be referred to in `with module` within their own signatures. This leads to some disconcerting module types:

```ocaml
# module type S = sig module M : sig end end;;
module type S = sig module M : sig  end end

# module rec M : S with module M = M = M;;
module rec M :
  sig module M : sig module M : sig module M : sig  end end end end

# module rec M : sig
    module N : S with module M = M
    module A : module type of N
    module B : module type of A
  end = M;;
        module rec M :
  sig
    module N :
      sig
        module M :
          sig
            module N :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
            module A :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
            module B :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
          end
      end
    module A :
      sig
        module M :
          sig
            module N :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
            module A :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
            module B :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
          end
      end
    module B :
      sig
        module M :
          sig
            module N :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
            module A :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
            module B :
              sig
                module M :
                  sig
                    module N : sig module M : sig  end end
                    module A : sig module M : sig  end end
                    module B : sig module M : sig  end end
                  end
              end
          end
      end
  end
```
including some which can cause the compiler real difficulty:
```ocaml
# module type S = sig module M : sig end module N = M end;;
module type S = sig module M : sig  end module N = M end
# module rec M : S with module M := M = M;;
module rec M : sig module N = M end
# module type T = module type of M;;
Fatal error: exception Stack overflow

Process ocaml-toplevel exited abnormally with code 2
```

Such module types would normally be rejected, but they are not caught when constructed using `with module` because `approx_modtype` ignores the right-hand side of `with module`. This patch adjusts this behavior to check that the right-hand sides of `with module`s are not recursive modules.

2018-04-06 17:20 UTC, Drup commented
The way you check for this is slightly disconcerting. I suppose you intend to provide a real error message instead? 

In general, wouldn't be better to extend `approx_modtype` to be aware of constraints? The test case you removed is safe (even if a bit contrived).

2018-04-09 10:20 UTC, lpw25 commented
> I suppose you intend to provide a real error message instead?

I'm not 100% what you mean. If you're asking if I'm going to change the code to improve the error message, then no probably not. It's the same message you get for any similar error, and fixing the terrible error messages in this part of the compiler is orthogonal to fixing this bug.

> In general, wouldn't be better to extend approx_modtype to be aware of constraints

You could possibly make it aware of module constraints, although I'm not totally sure that wouldn't introduce spurious errors.

You can't make it aware of type constraints because you cannot yet check the type expressions.

2018-07-25 14:37 UTC, lpw25 commented
I've rebased and added a Changes entry. This still needs review/approval. @Drup or @garrigue I think one of you is probably called for.

2018-07-28 08:01 UTC, garrigue requested changes
I don't see any test (only a removed one).
Or is there a test somewhere else?

I also do not understand why just checking for the presence of a module by that name helps. Couldn't there be an unrelated one in `env`?

2018-08-01 16:50 UTC, lpw25 commented
Thanks for the review. I've added a new test, and a comment to the code since it is a bit opaque.

We're just doing the same environment lookup that will be done later when creating the real (non-approximate) module type. When approximating module types the environment contains dummy bindings for all recursive modules, which will cause an error if you attempt to use them. This is the same mechanism which causes:

```ocaml
# module rec M : sig module N = M end = M;;
Characters 30-31:
  module rec M : sig module N = M end = M;;
                                ^
Error: Illegal recursive module reference
```

which I think is completely analogous to this case, and is why I am checking it this way.

2018-08-02 03:13 UTC, garrigue approved these changes

2018-08-02 08:58 UTC, merged