Fix and improve the documentation of dprintf.
ocaml/ocaml pull request #1967
Opened 2018-08-03 17:02 UTC by Drup

After remarks by @yallop and @pmetzger .

2018-08-03 17:15 UTC, pmetzger requested changes
Some suggested edits.

2018-08-03 17:15 UTC, pmetzger commented on stdlib/format.mli
> +  [formatter -> unit] which can be given to a format specifier [%t].
I'd remove "In particular, ", I think it's probably redundant.

2018-08-03 17:15 UTC, pmetzger commented on stdlib/format.mli
> +  This can be used as a replacement of {!asprintf} to delay formatting
"a replacement for" rather than "of" I think.

2018-08-03 17:15 UTC, pmetzger commented on stdlib/format.mli
> +  known. For example:
Perhaps: "Using the string returned by {!asprintf} in a
  formatting context forces formatting decisions to be taken in isolation, and
  the final string may be created prematurely.  {!dprintf} allows delay of
  such formatting decisions until the final formatting context is
  known."

2018-08-03 17:16 UTC, gasche commented
What about NEXT_VERSION as well, could you use 4.08? (It occurs twice in the file.)

2018-08-03 22:08 UTC, Drup commented
@gasche @pmetzger Done.

2018-08-04 06:36 UTC, gasche approved these changes

2018-08-04 06:37 UTC, merged