Doc clarification
ocaml/ocaml pull request #1984
Opened 2018-08-10 04:50 UTC by obscurans

See [MPR#7836](https://caml.inria.fr/mantis/view.php?id=7836). Clarifies the documentation on erasability of optional arguments.

2018-08-10 09:05 UTC, Octachron requested changes
I have few remarks but I think it is a good idea.

2018-08-10 09:05 UTC, Octachron commented on manual/manual/tutorials/lablexamples.etex
> +
I would rather not split this paragraph in two.

2018-08-10 09:05 UTC, Octachron commented on manual/manual/tutorials/lablexamples.etex
> +arguments.
You could maybe replace  `omitting all labels for all arguments` by `omitting all labels for all *other* arguments` or `all remaining arguments` to make it clear that optional arguments are excluded.

2018-08-10 13:57 UTC, pmetzger commented on manual/manual/tutorials/lablexamples.etex
> +
The split seems to be sensible to me since it makes the `Note` stand out more, but it's not a big deal either way.

2018-08-12 12:46 UTC, Octachron approved these changes
The changes looks good to me.

2018-08-13 05:49 UTC, nojb commented
In [MPR#7837](https://caml.inria.fr/mantis/view.php?id=7837), @obscurans observes that if warning 6 (label was omitted in the application of function) is active and an error, then it is in fact impossible to erase the optional arguments.

Should this be mentioned in the documentation as well? And more importantly, should we trigger warning 16 (unerasable optional argument) in this situation?

2018-08-13 06:55 UTC, Octachron commented
Since warning 6 is raised on function calls and can be locally suppressed , I am not sure if raising a warning on the definition site depending on the status of warning 6 at this point is useful. Nevertheless, it may make sense to mention this point in an extended description of warning 6.

2018-08-13 21:46 UTC, yallop commented
I agree with @Octachron here: it doesn't seem quite right to trigger warning 16 depending on warning 6, since the definition of a function and the calls to that function may be compiled with entirely different flags.  In fact, warning 16 already suffers from a similar issue: it assumes more than is justified about the calling context when abstract types are involved.  Here's an example:

```
# let f (type a) (x : a) ?y = x;;
Characters 24-25:
  let f (type a) (x : a) ?y = x;;
                          ^
Warning 16: this optional argument cannot be erased.
val f : 'a -> ?y:'b -> 'a = <fun>
# f succ 3;;
- : int = 4
```

That is, OCaml (invoked without flags) claims that the optional argument of `f` cannot be erased, but the next line demonstrates that it is in fact possible to call `f` without the optional argument.

2018-08-16 20:45 UTC, merged

2018-08-16 20:46 UTC, Octachron commented
I merged the current improvement, thanks @obscurans  !