Propagate register availability information through [Linearize]
ocaml/ocaml pull request #2068
Opened 2018-09-25 14:32 UTC by mshinwell

This patch propagates register availability information, as produced from phantom let expressions and the `Available_regs` forwards dataflow analysis, through the `Linearize` pass.  After that pass and after assembly emission the debugging information emitter is in a position to generate DWARF information, based on labels within the linearised code, knowledge as to the whereabouts of registers holding named values of variables during execution, and descriptions of the defining expressions of phantom lets.

This patch is based on both #2065 and #2067.  For the moment all new code is in changeset `ca88e4e`.

I would appreciate some careful review of this tricky patch.  The aim is not to disturb the availability information as the code is linearised.  Comments in the already-merged module `Available_regs` should be of help and I have identified some particular areas, by adding comments, where I found careful thought was needed in the `linear` function itself.

There should be no effect on code generation whether or not any availability information exists.

One thing I have realised is that the forwards dataflow analysis being done on `Mach` means that we cannot just repeat it after instruction scheduling, which may disturb the availability information.  Given that the three main target platforms (x86-64, AArch64 and RISC-V) do not have scheduling enabled then I currently propose to add an option to disable instruction scheduling and to refuse to generate full DWARF information on the remaining targets unless such option is set.  I think in practise this should be acceptable.  I think it is better to keep the dataflow analysis on `Mach` since it is both easier and more obviously analogous to the backwards dataflow analysis in `Liveness`.  If a real problem occurs here it is possible that the scheduling pass could be adjusted to preserve the availability information, though I think that might be tricky.

2018-10-17 15:16 UTC, lthls requested changes
I have reviewed this PR, and I believe it does not affect the normal operation of the compiler.
However, I have noticed several places were the availability information seems to be propagated or computed wrongly, and made comments.

2018-10-17 15:16 UTC, lthls commented on asmcomp/linearize.ml
> +    | _ -> cons_instr_same_avail (Lbranch lbl) n1
This looks wrong. You may need to pass `available_before` as an argument to this function.

2018-10-17 15:16 UTC, lthls commented on asmcomp/linearize.ml
> +                ~register_class:Proc.register_class)
Aren't you missing a `Set.diff` ?

2018-10-17 15:16 UTC, lthls commented on asmcomp/linearize.ml
> +           "available across" which is always empty). *)
This is correct because the `Available_regs` pass does the necessary fixpoint computation. Might be worth mentionning in the comment.

2018-10-17 15:16 UTC, lthls commented on asmcomp/linearize.ml
> +     block, cf. [Selectgen].) *)
The `Iname_for_debugger` operations have been removed by `linear` (see above). I believe the original code only needs to be updated to use the `available` fields from `first_insn`.
Unless you actually need the `Iname_for_debugger` instructions still, in which case you should update the code that removes them.

2019-03-06 13:30 UTC, mshinwell commented
I've rewritten and substantially improved the support for propagating availability information through `Linearize`; I will open another GPR to supercede this one (but will note the comments above).

2019-03-06 13:30 UTC, closed without merging