Signature local bindings
ocaml/ocaml pull request #2122
Opened 2018-10-26 15:38 UTC by trefis

This is the revamped version of #2016: it allows some type and module aliases to be bound in a signature without being exported.
The chosen syntax is the one that @garrigue proposed, which is reminiscent of destructive substitution:
```ocaml
type t := int
module M := N
```

A few things to note:
- support for module types (and class types?) wouldn't be absurd, but since the existing implementation of destructive substitution doesn't support them, I chose to omit them from this PR. I think we could add support (in both places) in a follow up PR.
- the restriction to aliases is enforced in the parser. Unfortunately it means that if one tries to write `type t := { x : int }` the error message will be pretty bad.
I could allow it in the parser and reject it later, e.g. from `Ast_invariants`, with a decent error message. But I'm hopeful that we could get good syntax error messages soon. Am I too optimistic?
- I don't know how to name these new constructs. My current approximation is "signature local binding", but something with "substitution" / "substituted" / etc. in the name could be nice as well.

2018-10-26 15:54 UTC, trefis commented
Also: the code to remove these local bindings calls `nondep`, which isn't necessary. It was just convenient because it's already there and will be needed for the generalized open construction.

@lpw25 just voiced (offline) that he'd rather not use `nondep` in that case and simply use `Subst`.
I'll push a commit changing that in a couple of days.

2018-10-26 17:21 UTC, alainfrisch commented
> I could allow it in the parser and reject it later, e.g. from Ast_invariants, with a decent error message.

IMO, that would be better.

2018-10-26 17:26 UTC, alainfrisch commented
Did you consider introducing new constructors in the AST (Parsetree and Typedtree) instead of adding a component to a tuple?  That would reduce the impact on e.g. ppx rewriting, and should not make the code really more complex.  Also, at the Typedtree level, you could use a more precise representation than the generic one (just a type expression, not a type declaration).

2018-10-26 17:33 UTC, trefis commented
> Did you consider introducing new constructors in the AST (Parsetree and Typedtree) instead of adding a component to a tuple? That would reduce the impact on e.g. ppx rewriting, and should not make the code really more complex. Also, at the Typedtree level, you could use a more precise representation than the generic one (just a type expression, not a type declaration).

I had a first implementation doing just that, but the churn was actually much bigger and I eventually gave up on it.
The current proposal is indeed a bit less precise, but I think the impact on ppxes should be roughly equivalent.
I could give it another go if you insist.

As for allowing the forbidden construction to parse and reject them later: I'll make the change; but I'd like to revisit that once we get menhir to generate nice syntax error messages.

2018-10-26 19:57 UTC, gasche commented
> But I'm hopeful that we could get good syntax error messages soon. Am I too optimistic?

Even with good support for error messages, LR messages will detect a situation of the sort `type t := <not a type>`: they will detect a failure on `{`. I don't think that we (as human error-message tuners) will have both the control and the courage to write different error message depending on whether the unexpected error message, at this point, is or not the prefix of a valid type declaration.

So you can reasonably hope to get "we were expecting a type (expression) here", but not "you are trying to write a type declaration, but only type synonyms are accepted", I think.

2018-10-29 10:47 UTC, trefis commented
> I don't think that we (as human error-message tuners) will have both the control and the courage to write different error message depending on ...

I'm not sure we'll have the control, as for the courage: we have it right now to produce it from a different part of the compiler, so I don't think it would make much difference.
But the rest of your message makes sense.

I updated the code to emit a proper error message from typemod (doing it in `Ast_invariant` wouldn't have been good enough since that's only called when a rewriter has been applied).

2018-10-31 11:57 UTC, trefis commented
I pushed two new commits:
- the first one switches the use of `nondep` to `Subst` for sig-local bindings. It also cleans up the code around that area (removing one `assert false`!).
- the second one adds support for `module M := F(A)`, whereas the initial version of the code only allow module aliases. This is consistent with what destructive substitution supports.
This commit also introduces specific constructors in the parsetree and typedtree: `P/Tsig_modsubst`. I will try again to do something similar for types and report back.

2018-10-31 13:40 UTC, trefis commented
OK I now also introduced a new constructor for type substitutions.
I think the thing that was annoying with my first experiment was that I tried to do the same thing that Alain suggested, i.e.
> use a more precise representation than the generic one (just a type expression, not a type declaration)

Which was very painful. I'm currently not doing that, I still use a type declaration but that's precisely what destructive substitution uses.
Again, I think if we want to change that, we should change both together (and definitely not in the present PR).

This should now be ready for review: the history is a bit less clean than I'd have hoped, but the whole diff should be easy to read.

2018-11-06 17:47 UTC, lpw25 requested changes
There's a few things that need fixing, but other than those this looks good to merge.

2018-11-06 17:47 UTC, lpw25 commented on parsing/parsetree.mli
> +     pms_synonym: Longident.t loc;
Maybe `pms_manifest` to match the type declaration case?

2018-11-06 17:47 UTC, lpw25 commented on parsing/parsetree.mli
> +        (* type t1  = ... and ... and tn  = ... *)
Accidental change to whitespace.

2018-11-06 17:47 UTC, lpw25 commented on parsing/parsetree.mli
> +  | Psig_typesubst of rec_flag * type_declaration list
This `rec_flag` should be removed because substitutions should all be "nonrec".

2018-11-06 17:47 UTC, lpw25 commented on ocamldoc/odoc_sig.ml
> +        | Parsetree.Psig_typesubst (rf, name_type_decl_list) (* FIXME *) ->
Maybe we can do better here. Perhaps @Octachron would like to think about how we want to display these in OCamldoc's output.

2018-11-06 17:47 UTC, lpw25 commented on typing/typemod.ml
> +type hidding_error =
Misspelling

2018-11-06 17:47 UTC, lpw25 commented on typing/typemod.ml
> +  | Invalid_subst_rhs of [ `Module | `Type ]
No real need for a polymorphic variant here.

2018-11-06 17:47 UTC, lpw25 commented on testsuite/tests/typing-sigsubst/sig_local_aliases_syntax_errors.compilers.reference
> +Error: Syntax error: 'end' expected
I think you need an error production in the parser to give this a better error message

2018-11-06 17:47 UTC, lpw25 commented on testsuite/tests/typing-sigsubst/sig_local_aliases.ml
> +
I suggest adding tests for `type ... and` and potentially recursive substitutions somewhere in this file.

2018-11-06 17:47 UTC, lpw25 commented on typing/typemod.ml
> +              if td.typ_kind <> Ttype_abstract || td.typ_manifest = None
What about private?

2018-11-06 17:47 UTC, lpw25 commented on typing/typemod.ml
> +            let newenv = Env.enter_module_declaration id md env in
This should sometimes be an alias.

2018-11-09 12:35 UTC, Octachron commented on ocamldoc/odoc_sig.ml
> +        | Parsetree.Psig_typesubst (rf, name_type_decl_list) (* FIXME *) ->
I will try to have a look.

2018-11-09 13:34 UTC, trefis commented
OK I pushed a few more commits addressing @lpw25's comments (there should be one commit per review comment).
I also updated the "language extensions" chapter of the manual to describe the new constructions (that I have named "local substitution[ declaration]s").

2018-11-09 17:00 UTC, lpw25 approved these changes
I think this is ready to merge now.

2018-11-12 10:13 UTC, merged