Fix new dynlink's initialisation checks
ocaml/ocaml pull request #2176
Opened 2018-11-30 10:31 UTC by lpw25

#1063 rewrote the various checks when loading shared libraries with dynlink in order to make them sound. However, the checks to ensure that a module is not used before it has been initialised were far too restrictive. For example, a module in a shared library could not refer to another library within the same shared library. This PR fixes that by updating the list of initialised units earlier. This PR also relaxes the "allowed units" check so that it only applies to implementation dependencies not interface dependencies -- which matches the previous behaviour and is necessary to deal with mli-only modules.

I also added a bunch of tests that exercise the various cases.

This PR should hopefully fix MPR#7876 -- although I haven't actually tried it.

This PR is on top of #2175 because that bug was causing problems with the use of packing added by #1063.

2018-11-30 21:53 UTC, ejgallego commented
I confirm this fixes Coq plugins in both build modes [using -pack and using aliases].

2018-12-01 09:19 UTC, gasche commented
cc @alainfrisch @chambart @mshinwell : we don't want to wait for too long between the merge of #1063 in trunk and a fix such as included in the present PR, so I think the urgency of this review is a bit higher than the usual.

2018-12-03 08:40 UTC, mshinwell commented
Ack, I will read this soon.

2018-12-03 09:30 UTC, gasche commented
( @lpw25, you could rebase now that #2175 is merged. )

2018-12-03 10:43 UTC, lpw25 commented
Rebased

2018-12-03 16:10 UTC, mshinwell requested changes

2018-12-03 16:10 UTC, mshinwell commented on testsuite/tests/lib-dynlink-initializers/test2_main.ml
> +   if its already loaded. *)
Please clarify what "its" refers to.  (And, "its" -> "it's".)

2018-12-03 16:10 UTC, mshinwell commented on testsuite/tests/lib-dynlink-initializers/test3_main.ml
> +   in the shared library if it is already loaded. *)
Same comment as above regarding "it is".

2018-12-03 16:10 UTC, mshinwell commented on testsuite/tests/lib-dynlink-initializers/test5_main.ml
> +   another shared libary can refer to modules of that library if they
Typo "libary".  Also maybe name the libraries "A" and "B" so we can make "that library" precise.

2018-12-07 12:44 UTC, mshinwell approved these changes

2018-12-07 12:45 UTC, mshinwell commented
This is OK to merge after the `Changes` file has been updated.

2018-12-08 15:15 UTC, merged