Introduce a script for checking file permissions
ocaml/ocaml pull request #2274
Opened 2019-02-28 17:03 UTC by shindere

this GPR is a follow-up to the discussion that took place in GPR#2270.

The proposed script makes sure files with an executable permission really
diserve it, meaning they are either boot/ocaml{c,lex} or scripts
starting with #!.

It will then become possible to use this script in our various CI
solutions but this can happen in future PRs.

Any comment regarding the implementation is welcome.
In particular, the script only looks for permissions like 755,
perhaps this should be improved e.g. with a regexp?

2019-03-01 08:22 UTC, XVilka commented
Maybe it make sense to set it as a git hook as well?

2019-03-01 08:29 UTC, shindere commented
Anton Kochkov (2019/03/01 08:22 +0000):
> Maybe it make sense to set it as a git hook as well?

Perhaps, I don't know. Would it be okay, in a hook, to test the whole
repo rather than just the files that are modified by the commit? Because
you mean a commit hook, right?

2019-03-01 08:56 UTC, dra27 commented
@shindere - thanks for writing the script! It would be good to update our pre-commit githook too, which already has the necessary machinery just to examine the files in the commit - I’ll push something later, if you don’t get there first!

2019-03-01 09:39 UTC, shindere commented
David Allsopp (2019/03/01 00:56 -0800):
> @shindere - thanks for writing the script! It would be good to update
> our pre-commit githook too, which already has the necessary machinery
> just to examine the files in the commit - I’ll push something later,
> if you don’t get there first!

I'd prefer if you can have a look at it, thanks!

It could even be done in another PR.

2019-03-01 12:57 UTC, shindere commented
Rebased and updated to take into account a lunch-time comment given by
@xavierleroy:

It is actually important that
`testsuite/tests/lib-unix/unix-execvpe/subdir/script2`
does not begin with a #! because the very purppose of the test it
belongs to is to check how exec behaves on such files.

2019-03-01 13:44 UTC, xavierleroy commented
Thank you for the attention you gave to `testsuite/tests/lib-unix/unix-execvpe/subdir/script2`.  The `exec` family of system calls behave slightly differently on scripts that start with `#!/bin/sh` than on scripts that don't start with `#!`, so it is intentional to test both.

2019-03-01 13:46 UTC, shindere commented
Okay, many thanks for having clarified this!

2019-03-01 13:46 UTC, xavierleroy reviewed
Looks good to me.  I'm sure someone else will suggest the use of git attributes to mark the exceptions, but I don't mind.

I'm the one who suggested the name `check-file-modes` for this script but perhaps `check-file-permissions` would be more idiomatic.

2019-03-01 14:02 UTC, shindere commented
Xavier Leroy (2019/03/01 05:46 -0800):
> xavierleroy commented on this pull request.
> 
> Looks good to me.  I'm sure someone else will suggest the use of git
> attributes to mark the exceptions, but I don't mind.

We discussed it with @gasche yesterday and agreed it's okay to go ahead
that way for now, we can always do it differently later if the need
appears.

> I'm the one who suggested the name `check-file-modes` for this script
> but perhaps `check-file-permissions` would be more idiomatic.

Done. Didn't rename the branch though.

2019-03-01 15:38 UTC, xavierleroy requested changes
Typo + small portability issue.

2019-03-01 15:38 UTC, xavierleroy commented on tools/check-file-permissions
> +  if [ x`head -c2 $1` != x'#!' ]; then
Just to ruin your day: the `-c` option to `head` is not standard (see https://pubs.opengroup.org/onlinepubs/9699919799/utilities/head.html#tag_20_57) and is not implemented in OpenBSD.  (But FreeBSD and MacOS have it.)  So, your script will not run everywhere.  

Possible alternative: `if head -n 1 "$1" | grep -q '^#!' `.

2019-03-01 15:38 UTC, xavierleroy commented on tools/check-file-permissions
> +    echo $1 does not seem to diserve its executable permission
"deserve", not "diserve".

2019-03-01 15:50 UTC, shindere commented
Well, thanks for the useful feedback! I have to say, it didn't even come
to me that there could be a portability issue with this option of
`head` so many thanks for having thought about it.


Proposed fixes applied, thanks again!

2019-03-01 15:56 UTC, dra27 commented
Just to say that I've got an update to `check-typo` to do this, as that propagates to the githook … just debugging one weirdness with the awk script (bashes head against desk)

2019-03-02 10:37 UTC, xavierleroy requested changes

2019-03-02 10:37 UTC, xavierleroy commented on tools/check-file-permissions
> +  if head -n 1 "$1" | grep -q '^#!'; then
You need to invert the test.  It's not because I suggest something that you should not think before implementing the suggestion :-)

2019-03-02 10:49 UTC, shindere commented
Xavier Leroy (2019/03/02 02:37 -0800):
> You need to invert the test.  It's not because I suggest something
> that you should not think before implementing the suggestion :-)

Blind devotion and its dangers...

It's fixed and tested, this time, thanks, and sorry.

2019-03-21 18:39 UTC, shindere commented
This is superseeded by #2298, thus closing.

2019-03-21 18:39 UTC, closed without merging