Add a few utility functions in Misc
ocaml/ocaml pull request #2284
Opened 2019-03-05 14:58 UTC by mshinwell

This GPR provides a few straightforward functions in `Misc` that are required by the forthcoming work on symbol types.  I don't think there is value in breaking this patch down into smaller pieces, given current time constraints.

2019-03-05 15:24 UTC, trefis reviewed
The `Option` module exists in the stdlib. Shouldn't you try using it, instead of `Misc.Stdlib.Option`?
Also, the one in `Misc` I believe duplicates some of the functions of the one in the stdlib. Perhaps it would be better to look into cleaning `Misc.Stdlib` instead of growing it even more.

2019-03-05 15:24 UTC, trefis commented on utils/misc.ml
> +      Format.pp_print_string ppf t
Pffff.

2019-03-05 15:24 UTC, trefis commented on utils/misc.ml
> +      | Some contents1, Some contents2 -> f contents1 contents2
Would that function make sense in the stdlib?

2019-03-05 15:36 UTC, mshinwell commented
Indeed, I think these probably predate the support in the `Stdlib` for `Option` that I had forgotten about.  I will see how much we can remove from `Misc`.

2019-03-06 10:44 UTC, mshinwell commented
@trefis Please review again.  I have removed the functions from `Misc.Stdlib.Option` that are now in the stdlib.

2019-03-06 11:57 UTC, trefis requested changes
The cleanup of `Misc.Stdlib.Option` is nice!
Adding a printer in there seems reasonable.

The addition of `Misc.protect_writing_to_file` is also fine.

I would remove the alias to `Format.pp_print_string` from `Misc.Stdlib.String` though.

2019-03-06 11:57 UTC, trefis commented
Also, I tend to agree with Alain: I'm not sure there is much value in a changelog entry for that PR.

2019-03-06 12:19 UTC, mshinwell commented
The `print` function in `String` was put there for a reason: I'd like modules to have a uniform interface, which includes printing for all data structures.

2019-03-06 12:38 UTC, Drup commented
> The `print` function in `String` was put there for a reason: I'd like modules to have a uniform interface, which includes printing for all data structures.

I agree with that on principle, the issue is dependency order of stdlib modules.

At some point, we need to have a serious though about the exact dependency orders we want for the stdlib modules. I remember @dbuenzli being pretty burned by that for the `UChar` module (iirc).

2019-03-06 12:46 UTC, mshinwell commented
@Drup Well, we need to have a serious discussion as to how printing can be added to the data structure modules in the stdlib.  Let's do that elsewhere though...

2019-03-06 12:51 UTC, dbuenzli commented
> I remember @dbuenzli being pretty burned by that for the `UChar` module (iirc).

Just for the ref this was https://caml.inria.fr/mantis/view.php?id=7500

2019-03-13 10:32 UTC, trefis commented
> I agree with that on principle, the issue is dependency order of stdlib modules.

We're not talking about the stdlib here, only of `Misc.Stdlib`.

Since people think it's fine I'll retract my comment and approve.

2019-03-13 10:33 UTC, trefis approved these changes
Feel free to merge once you've rebased.

2019-03-15 11:28 UTC, merged