Replace caml_int_compare and caml_float_compare with primitives
ocaml/ocaml pull request #2324
Opened 2019-03-13 14:22 UTC by gretay-js

Add new compiler primitives to implement comparison operations that return int (not bool) result. These operations are important for IntMap.
Instead of calls to `caml_int*_compare` and `caml_float_compare`, emit native code directly.  This enables some optimizations when arguments of compare operations are statically known constants.  There is no change to machine-specific code generation, because the new primitives are translated in `cmmgen` to existing cmm constructs.

Recently, PR #2250 @smuenzel-js   proposed to improve these C functions.  It will still be useful for bytecode and int64 on 32-bit targets.  For native code, the current PR gives better performance than PR #2250.

Benchmarking on amd64 target Intel(R) Xeon(R) Gold 6144 on two microbenchmarks:

test5.ml: Tight loop example from PR #2250
```
┌───────────────────┬─────────────────┬─────────────────┬───────┬────────────┬─────────────┬───────┐
│                   │    instructions │      Difference │     % │ clock (ms) │  Difference │     % │
├───────────────────┼─────────────────┼─────────────────┼───────┼────────────┼─────────────┼───────┤
│    test5-base.exe │ 280,092,029,458 │               0 │ 1.000 │ 29,386.268 │           0 │ 1.000 │
│  test5-pr2250.exe │ 268,091,554,395 │ -12,000,475,063 │ 0.957 │ 29,439.480 │      53.212 │ 1.002 │
│ test5-compare.exe │ 220,056,326,489 │ -60,035,702,969 │ 0.786 │ 17,720.873 │ -11,665.395 │ 0.603 │
└───────────────────┴─────────────────┴─────────────────┴───────┴────────────┴─────────────┴───────┘
```

test6.ml: IntMap loop that calls add, remove, find, and mem.
```
┌───────────────────┬────────────────┬────────────────┬───────┬────────────┬────────────┬───────┐
│                   │   instructions │     Difference │     % │ clock (ms) │ Difference │     % │
├───────────────────┼────────────────┼────────────────┼───────┼────────────┼────────────┼───────┤
│    test6-base.exe │ 72,942,680,772 │              0 │ 1.000 │ 13,188.722 │          0 │ 1.000 │
│  test6-pr2250.exe │ 72,034,245,520 │   -908,435,252 │ 0.988 │ 13,126.140 │    -62.582 │ 0.995 │
│ test6-compare.exe │ 68,470,617,181 │ -4,472,063,591 │ 0.939 │ 12,640.141 │   -548.581 │ 0.958 │
└───────────────────┴────────────────┴────────────────┴───────┴────────────┴────────────┴───────┘
```

Inria's precheck all tests pass (build # 206).

2019-04-10 14:23 UTC, stedolan commented on asmcomp/cmmgen.ml
> +      let op4 = Cop(Ccmpf(CFeq), [a2; a2], dbg) in
This looks correct, but it took me a while to puzzle it out and a comment would help!

(My understanding is: if either operand is `nan`, then `op1 = op2 = 0` and `op3 - op4` orders `nan` before non-`nan` values. If neither operand is `nan`, then `op3 - op4` is `0` (both are `1`), so `op1 - op2` gives the answer)

2019-04-26 06:23 UTC, smuenzel-js commented
We probably just need to rebase to fix the checks (I've done that here, if you want to pull: https://github.com/smuenzel-js/ocaml/tree/compare-primitive) and add some comments in the section @stedolan mentioned, and then this should be ready for review, right?

2019-04-30 09:38 UTC, gretay-js commented
Rebased and updated the comment.
Thanks @stedolan for the review and @smuenzel-js for help!

2019-08-26 11:01 UTC, gretay-js commented
Ping... there wasn't any objection to this being merged, right?

2019-09-13 07:23 UTC, smuenzel-js commented
@stedolan : ping

2020-01-30 12:20 UTC, smuenzel commented
one more ping :)

2020-01-30 14:15 UTC, lthls requested changes
The handling of 32-bit architectures needs to be fixed. In particular, there are a number of suspect failures in the CI that need to be looked at. You can probably reproduce the failures by configuring your compiler to use a 32-bit toolchain (see [this opam file](https://github.com/ocaml/opam-repository/blob/master/packages/ocaml-variants/ocaml-variants.4.09.0%2B32bit/opam) for the configure flags).

2020-01-30 14:15 UTC, lthls commented on asmcomp/cmm_helpers.ml
> +    end
I think you could handle the cases where `a1` and `a2` are `Cconst_int` and `Cconst_natint` too.

2020-01-30 14:15 UTC, lthls commented on asmcomp/cmmgen.ml
> +      mk_compare_ints dbg a1 a2
I think this code is wrong: on 32-bit architectures, 64-bit integers are not translated to machine integers, but to pairs of integers. I'm not sure exactly what will happen, hopefully a type mismatch error later in the compilation pipeline.

2020-01-30 14:15 UTC, lthls commented on asmcomp/cmmgen.ml
> +         and op4 is 0 if and only if a2 is NaN. *)
There's a nice comment in `runtime/floats.c`, on function `caml_float_compare_unboxed`, that explains the choice of operations. I'd suggest to add cross references at both places to keep them consistent with each other.

2020-03-18 14:00 UTC, gretay-js commented on asmcomp/cmmgen.ml
> +      mk_compare_ints dbg a1 a2
Fixed. 
I have already had it working on another branch but somehow the fix was not included here after all the rebases, sorry.

2020-03-18 14:00 UTC, gretay-js commented on asmcomp/cmmgen.ml
> +         and op4 is 0 if and only if a2 is NaN. *)
Done

2020-03-18 14:11 UTC, gretay-js commented on asmcomp/cmm_helpers.ml
> +    end
The code already handles the case of 
https://github.com/ocaml/ocaml/blob/040ec34dd1bab9b9ab64e492a94c03c8c906ebb0/asmcomp/cmm_helpers.ml#L279
and 
https://github.com/ocaml/ocaml/blob/040ec34dd1bab9b9ab64e492a94c03c8c906ebb0/asmcomp/cmm_helpers.ml#L284

Are there other combinations with Cconst_* that it should check ?

2020-03-18 14:17 UTC, lthls commented on asmcomp/cmm_helpers.ml
> +    end
I was referring to cases where one is `Cconst_int` and the other is `Cconst_natint`. They're compatible.

2020-03-18 16:13 UTC, gretay-js commented on asmcomp/cmm_helpers.ml
> +    end
Ah, they are! I've just  updated the code to handle all 4 cases uniformly.

2020-03-19 13:50 UTC, lthls approved these changes

2020-03-20 17:30 UTC, lthls commented
I'm leaving the week-end for other developers to voice objections, and will merge on Monday unless somebody complains strongly enough.

2020-03-24 11:37 UTC, gretay-js commented
@lthls Thank you!

2020-03-26 09:58 UTC, merged

2020-03-26 09:59 UTC, lthls commented
I'll pretend we're still Monday.
Thanks @gretay-js for the contribution !