Remove SPARC backend
ocaml/ocaml pull request #659
Opened 2016-07-05 11:01 UTC by mshinwell

The SPARC backend, which only generates 32-bit code, is difficult to test these days due to lack of available hardware.  It is suspected that there is no actual use for this backend in the wild at the moment.  The maintenance burden of maintaining this backend would seem to be higher than any extra cost (due to bitrot) that its removal would incur in the future should it be resurrected and ported to modern SPARC64 hardware.

2016-07-05 11:41 UTC, johnwhitington commented
I have about half a dozen customers of my PDF software using this backend, the most recent of whom purchased from us in 2015.

Now, since I'm not able to contribute to its maintenance, or willing to pay for someone to contribute to it, I can hardly complain. But it is still in use.

2016-07-05 11:48 UTC, mshinwell commented
Hmm.  We may need to keep it around in that case.  Do you know if the target is Solaris or Linux?

2016-07-05 11:52 UTC, avsm commented
If there's an actual user (thanks @johnwhitington!) then I can dig out SparcStation hardware in the Computer Lab.  One issue is that Linux kernel support for sparc32 has lagged for years, so it's likely that an old Solaris installation is the only practical OS target to support.  I don't have a copy of Solaris lying around...

2016-07-05 11:55 UTC, johnwhitington commented
Solaris 8 in the most recent case. The customer compiled it themselves.

Because of the following issue I know OCaml builds ok on SPARC at least up to 4.01.0:

http://caml.inria.fr/mantis/view.php?id=6214

In this instance, I compiled it by remote login to the customer's machine.

@avsm Thanks, but I think I still have access to sparc hardware via polarhome.com, if I can dig out the login details, so I'm willing to test build before 4.04.

2016-07-05 12:16 UTC, xavierleroy commented
@johnwhitington : I have a polarhome.com account as well, but recently they reduced disk quotas so much that you can't even check out the OCaml source tree, let alone build it...

2016-07-05 12:23 UTC, johnwhitington commented
@xavierleroy Oh dear. I remember having to disable camlp4 last time (when it was in-tree), because there wasn't enough disk space to do the build, but I didn't realise it had got so bad.

2016-07-10 12:10 UTC, alainfrisch commented
(Closing the PR, since it seems this backend is not going away soon.  Feel free to continue using this thread to discuss how to best access such hardware for testing purposes.)

2016-07-11 00:48 UTC, DemiMarie commented
Could we cross-compile from a different architecture, and they run the binaries?

2016-07-11 00:50 UTC, DemiMarie commented
This is a motivation to provide a backend – even an unoptimized one – that generates C code and/or LLVM IR, to provide platform independence.

2016-07-11 11:28 UTC, avsm commented
> This is a motivation to provide a backend – even an unoptimized one – that generates C code and/or LLVM IR, to provide platform independence.

The bytecode `ocamlc` compiler is a (mostly) unoptimized and highly portable backend that only needs a C compiler.

2016-07-11 13:04 UTC, bobzhang commented
hi @xavierleroy , we have solaris sparc machine, we don't use it in production for ocaml code base, but I can help set up a jenkins job, where should I report failures?

2016-07-18 19:53 UTC, const-rs commented
I have SPARC/Solaris machine (last OpenSolaris). Current ocaml d6c72fc82a8950851da5f121b80a4e1c8bff377a builds and works well enough for me.

The only problem I had - OPAM compiled with 4.02 (its lib-ext does not compile with current trunk) crashed several times with SIGSEGV somewhere deep in GC. Though I can not reproduce it now (perhaps it was a problem with installation).

2016-10-05 12:38 UTC, damiendoligez commented
@bobzhang I can see a few options:
- set it up as a slave for Inria's CI system (needs you to accept ssh connections from Inria)
- set it up as a Travis slave (if that's possible)
- set it up in your own Jenkins and send reports to ocaml-ci-notifications(at)inria.fr, which is the address used by Inria's CI system. BTW I can give you access to the Inria CI system if you want.

2016-10-05 13:52 UTC, bobzhang commented
@damiendoligez I will try to set up a Jenkins job this week and see what can be improved

2017-04-04 14:15 UTC, mshinwell commented
Reopening this pull request.  Having a backend which the core team has no means of testing seems untenable, roughly speaking.

@damiendoligez @bobzhang Have there been any updates on trying to get one of these machines in the CI?  I think it needs to be running Solaris as per the discussion above.

2017-04-07 12:10 UTC, mshinwell commented
I checked with @johnwhitington and the conclusion was that it was ok to remove the SPARC backend now.  The code concerns compiles with versions of OCaml going back some way, and in any case, the bytecode version could always be used.

If there are no further objections soon then I'll rebase this patch for the backend's removal.

2017-04-07 15:23 UTC, damiendoligez commented
@mshinwell as far as I know, the Sparc CI was never live.

2017-04-07 17:32 UTC, xavierleroy commented
All right, it is clear now that no one wants to pay the (financial and human) costs of proper SPARC/Solaris support in OCaml.  I'm in favor of removing this compiler back-end.

2017-04-10 09:24 UTC, mshinwell commented
This is ready for review.

2017-04-10 09:34 UTC, xavierleroy requested changes
You're removing too much stuff, see below.  Remember, this is just native-code SPARC support that is being removed, not bytecode support.

2017-04-10 09:34 UTC, xavierleroy commented on asmrun/signals_asm.c
> -  || (defined(TARGET_sparc) && defined(SYS_solaris))
Explain why you're touching s390x support, here?

2017-04-10 09:34 UTC, xavierleroy commented on configure
> -  sparc*-*-*|hppa*-*-*|arm*-*-*|mips*-*-*)
Don't remove, SPARC is still supported in bytecode, and this alignment business affects the bytecode system.

2017-04-10 09:34 UTC, xavierleroy commented on otherlibs/num/.depend
> -bng_sparc.$(O): bng_sparc.c
Don't remove, this can still help with the bytecode version of the library

2017-04-10 09:34 UTC, xavierleroy commented on otherlibs/num/bng_sparc.c
> -/**************************************************************************/
More generally, don't touch otherlibs/num at all

2017-04-10 11:35 UTC, mshinwell commented on configure
> -  sparc*-*-*|hppa*-*-*|arm*-*-*|mips*-*-*)
Ah yes, sorry, I misread that as being for native only.

2017-04-10 11:35 UTC, mshinwell commented on asmrun/signals_asm.c
> -  || (defined(TARGET_sparc) && defined(SYS_solaris))
I'm not -- the s390x line is still there, just without the backslash...

2017-04-10 11:35 UTC, mshinwell commented on otherlibs/num/.depend
> -bng_sparc.$(O): bng_sparc.c
Resurrected

2017-04-10 11:35 UTC, mshinwell commented on otherlibs/num/bng_sparc.c
> -/**************************************************************************/
Likewise

2017-04-11 08:50 UTC, xavierleroy approved these changes

2017-04-11 08:50 UTC, xavierleroy commented
Looks good to me.  Merging in trunk.

2017-04-11 08:50 UTC, merged

2025-10-07 17:35 UTC, glaubitz commented
> The SPARC backend, which only generates 32-bit code, is difficult to test these days due to lack of available hardware. It is suspected that there is no actual use for this backend in the wild at the moment. The maintenance burden of maintaining this backend would seem to be higher than any extra cost (due to bitrot) that its removal would incur in the future should it be resurrected and ported to modern SPARC64 hardware.

I'm super late to the party, but in case anyone is interested, Oracle engineers actually ported the SPARC backend to 64 bits. The patch can be found [here](https://github.com/sparclinux/ocaml/commit/6125e690f956da35914ae514a204ae662ca33059).

If someone is interested on hacking on 64-bit SPARC, there are two fast SPARC servers running both Debian unstable as well as Solaris 11.4 available in the [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm).