Optimize away some physical equality
ocaml/ocaml pull request #850
Opened 2016-10-11 14:24 UTC by chambart

Physical equality on structurally different values is always false. This patch allows to handle some cases. The need arise when evaluating some functions that use it to avoid some computation. For instance in `Set.add` test if the added value is already present to avoid rebuilding the same set.

```OCaml
    let rec add x = function
        Empty -> Node(Empty, x, Empty, 1)
      | Node(l, v, r, _) as t ->
          let c = Ord.compare x v in
          if c = 0 then t else
          if c < 0 then
            let ll = add x l in
            if l == ll then t else bal ll v r
          else
            let rr = add x r in
            if r == rr then t else bal l v rr
```

This change allows some of those uses to be eliminated.

2016-12-27 10:56 UTC, mshinwell requested changes

2016-12-27 10:56 UTC, mshinwell commented on middle_end/simplify_primitives.ml
> +  | _ -> false
Please make both of these matches exhaustive.

2016-12-27 10:56 UTC, mshinwell commented on middle_end/simplify_primitives.ml
> +      not (Tag.equal tag1 tag2) ||
Indentation needs fixing for these two stanzas (also on line 69 too).
I would also recommend following the GNU convention of putting the `||` at the start of each line of a multi-line conditional; I think it's easier to follow.

2017-03-07 10:09 UTC, mshinwell commented
@chambart Ping

2017-03-16 08:39 UTC, mshinwell commented on testsuite/tests/asmcomp/is_static_flambda.ml
> +    let eq = v == v in
These tests might as well check that `eq` is as expected, no?

2017-03-16 08:41 UTC, mshinwell commented
I made one comment, but OK otherwise.  We need to wait for @lpw25 to review too.

2017-03-16 08:42 UTC, mshinwell commented
Ah, this should have a Changes entry too, I think.

2017-03-17 10:11 UTC, mshinwell approved these changes

2017-05-04 16:02 UTC, mshinwell commented
@chambart Please add a Changes entry and merge to trunk, thanks.

2017-07-20 13:31 UTC, alainfrisch commented
Ping @chambart

2017-07-31 15:31 UTC, mshinwell commented on testsuite/tests/asmcomp/is_static_flambda.ml
> +    let eq = v == v in
Actually I think this is fine as-is.

2017-07-31 15:32 UTC, mshinwell commented
I've added the Changes entry and merged with current trunk.  I will merge into trunk assuming CI passes.

2017-08-01 07:04 UTC, merged