Add location information to Lswitch
ocaml/ocaml pull request #859
Opened 2016-10-13 11:30 UTC by mshinwell

This patch passes the location information that Matching already knew about to the code for generating `Lswitch`, which is now equipped with a location.  This can then be transported through to `Cswitch` (cf. #851).

At present this patch will only compile with the bytecode compiler.  After #851 has been dealt with I will add the missing pieces.

2017-03-07 08:51 UTC, mshinwell commented
The missing pieces of code here, to transport the location information through to Cmmgen, have now been added.

The switch compilation code in `bytecomp/` still uses `Location.t` rather than `Debuginfo.t`; conversion from the latter to the former will lose inlined frame information.  This doesn't matter since the location information on switch statements is not used for backtraces.

2017-03-10 16:05 UTC, ghost requested changes

2017-03-10 16:05 UTC, diml commented on bytecomp/matching.ml
> +    let v = name_pattern "*match*" cls in
Why this change?

2017-03-10 16:45 UTC, mshinwell commented on bytecomp/matching.ml
> +    let v = name_pattern "*match*" cls in
This is a hack to hide this kind of variable from being seen in the debugger.  Ideally we would have a flag on `Ident.t` to enable this to be represented.  I did wonder about removing this change from this patch but in fact I think it should maybe stay, and we should consider the `Ident.t` change in due course (which could clean up "*opt", etc.)

2017-03-15 15:09 UTC, diml commented on bytecomp/matching.ml
> +    let v = name_pattern "*match*" cls in
Ok

2017-03-15 15:09 UTC, ghost approved these changes

2017-03-15 15:09 UTC, merged