Uniform `-I` treatment
ocaml/ocaml pull request #8942
Opened 2019-09-15 22:25 UTC by dbuenzli

While trying to implement the `OCAMLPATH` [proposal](https://github.com/ocaml/ocaml/issues/8898) I noticed the toolchain treats inexisting directories passed to `-I` in different ways:

```shell
> touch a.ml 
> ocaml -I +doesnotexist a.ml       # toplevel 
> ocamlc -c -I +doesnotexist a.ml    # byte compile 
> ocamlc -I +doesnotexist a.ml       # byte link 
> ocamlopt -c -I +doesnotexist a.ml  # native compile 
> ocamlopt -I +doesnotexist a.ml     # native link (c linker warning) 
ld: warning: directory not found for option '-L/Users/dbuenzli/.opam/4.08.0/lib/ocaml/doesnotexit' 
> ocamldep -I +doesnotexist a.ml 
Bad -I option: /Users/dbuenzli/.opam/4.08.0/lib/ocaml/doesnotexit: No such file or directory 
[...] 
> ocamlc -depend -I +doesnotexist a.ml
Bad -I option: /Users/dbuenzli/.opam/4.08.0/lib/ocaml/doesnotexist: No such file or directory
```

Note that the `+` is irrelevant here, the tools behave the same way if you pass an arbitrary inexisting path `/that/does/not/exist`. To sum up:

1. `ocamldep` and `ocamlc -depend` is the only tool that checks for include directory existence: if the include does not exist it exits with code 2.
2. Calls to the C linker pass unchecked `-I` arguments to the C linker as is which does (at least on macOS) check for directory existence and thus yields a warning from the linker.
   
Among sound harmonizing alternatives are the following:

1. The toolchain always check the existence of includes (for `OCAMLPATH` if the include is a `+` it must exist in one of the directories mentioned in `OCAMLPATH`). Inexistence may warn (zero exit code) or error (non zero exist code)
2. The toolchain never check for existence of includes.

It would likely better to do 1. but I suspect this may break certain build systems. So this PR implements 2 for the time being (1 with warning might be an option in the future) as follows:

1. `ocamldep` and `ocamlc -depend` no longer check the `-I` for existence.
   (I suspect the relevant code should in fact use `Load_path` but this can 
    be done in another PR).
2. Calls to the C linker only pass `-I` directories that do exist on the file system.

Thanks to @gasche for his private feedback on the issue.

2019-09-15 22:29 UTC, dbuenzli commented on utils/load_path.ml
>      with Sys_error _ ->
Note that the original code hides permission errors. This is likely a bad idea but I didn't try to fix this in this PR (The code paths for `ocamldep` do not do this).

2019-09-16 08:20 UTC, trefis approved these changes
LGTM.

2019-09-16 08:26 UTC, xavierleroy commented
I don't understand the motivations for this PR.

The directories passed to ocamldep -I are source directories.  It makes sense that they must exist.

The directories passed to ocamlopt -I are installation directories, where compiled files are eventually installed.  If you're testing a library before installing it, for example, it could make sense that an installation directories don't exist yet.  

One thing you might want to do is to filter out installation directories that don't exist before passing them to the C compiler / linker.  But removing the error message in ocamldep is just wrong.

2019-09-16 08:28 UTC, xavierleroy requested changes

2019-09-16 08:28 UTC, xavierleroy commented on Changes
> +
I oppose this change.

2019-09-16 09:13 UTC, dbuenzli commented
> I don't understand the motivations for this PR.

It stems from looking at what affects changing `Misc.expand_directory` (that is the `-I +dir` notation handling) from returning a single directory to a list of directories (see `OCAMLPATH` [proposal](https://github.com/ocaml/ocaml/issues/8898)).

> The directories passed to ocamldep -I are source directories. It makes sense that they must exist.

Right, that was not entirely clear to me (or that it would always be that way in the future).

Currently in `ocamldep`, `-I +dir` will expand to a single directory (namely `$(ocamlc -where)/dir`). With the `OCAMLPATH` proposal this expands to a list of directories some of which are *expected* not to exist. If you don't have objections to the proposal itself something should be done here, either:

1. We don't treat the `+` notation at all for `ocamldep` which would be consistent with your interpretation of `-I` for `ocamldep` since `+dir` refers to install directories (or say compilation object directories). This basically means removing [this line](https://github.com/ocaml/ocaml/blob/5c7c619d4d335eddc58a0c5e889bb71174b0f829/driver/makedepend.ml#L84). 
2. We don't do anything. Using ocamldep with `-I +dir` and an `OCAMLPATH` search path with multiple directories will likely always error since `dir` is not expected to exist in all of them. 
2. For `ocamldep` we check at least one of the directories exists in the `OCAMLPATH` when we expand the `+` notation and error if that is not the case.
3. We don't check `-I`'s directory existence (this PR).

2019-09-16 13:36 UTC, xavierleroy commented
Thanks a lot for the explanations, it's much clearer to me now.

The OCAMLPATH proposal is not getting much traction yet, so it's good to think in advance of its consequences, but too early to change the master branch in preparation for its inclusion.

Personally I would never use `ocamldep -I +foo`, because I put dependencies on source files only.  Some users may be tempted to do `ocamldep -I +foo` so that their sources are recompiled if the package installed in `+foo` is updated.  But I think it doesn't work reliably, and, worse, can cause recompilations within `+foo` (if source .ml/.mli files are installed and the timestamps are wrong).

Other opinions welcome.

2020-02-11 15:05 UTC, damiendoligez commented
I'd be inclined to remove the `-I +foo` option for `ocamldep` (and `ocamlc -depend`) but it's hard to tell how many users' workflows it will break. (my bet: very few)

2022-09-30 14:56 UTC, dbuenzli commented
Let's decrement that pull request counter.

2022-09-30 14:56 UTC, closed without merging