Fixes to ArrayLabels documentation
ocaml/ocaml pull request #9024
Opened 2019-10-07 21:43 UTC by foocraft

- Removal of string arguments from exceptions in docs
- Changed references to `ArrayLabels` instead of `Array` whenever
  a labeled argument is present
- Fixes to code examples using the wrong argument(wrong name, or missing label)

There are many other references to `Array` in the documentation. Not sure if those should be changed as well.

2019-10-08 08:23 UTC, dra27 requested changes
Thanks for taking this on!

The reason this module refers to `Array` and not `ArrayLabels` is because it's intended to be used by `open StdLabels`, where the `Array`, `Bytes`, `List` and `String` modules are all replaced by their labelled counterparts. So the paradigm is:

```ocaml
open StdLabels

let everything = Array.create_matrix ~dimx:42 ~dimy:42 42
```

and hence the deprecation warning more meaningfully refers to `Array.make_matrix` because it's expected that's what you'd write (so the `@@ocaml.deprecated` attributes should definitely keep the `Array.` references).

For the rest (and for the other labelled modules) I'd suggest we could get rid of the module name entirely which removes the ambiguity (and can be applied to the other functions, as per your question) - so instead of `[Array.make_matrix …]` just have `[make_matrix …]` and the same with the cross-references (so instead of `{!ArrayLabels.make_matrix}` just `{!make_matrix}`). What do you think of that, @Octachron?

It's very good to remove the strings from the `Invalid_argument` descriptions, as it discourages matching on them - please could you upgrade them completely to use `@raise`, though (the documentation comments pre-date the availability of `@raise`, I think). I've put those as code suggestions.

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   Raise [Invalid_argument]
```suggestion
   @raise Invalid_argument
```

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   Raise [Invalid_argument]
```suggestion
   @raise Invalid_argument
```

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +  [@@ocaml.deprecated "Use ArrayLabels.make_matrix instead."]
I think should stay as `Array.make_matrix`

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   {!ArrayLabels.make_matrix}. *)
```suggestion
   {!make_matrix}. *)
```

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   Raise [Invalid_argument] if [pos] and [len] do not
```suggestion
   @raise Invalid_argument if [pos] and [len] do not
```

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   Raise [Invalid_argument] if [pos] and [len] do not
```suggestion
   @raise Invalid_argument if [pos] and [len] do not
```

2019-10-08 08:23 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   Raise [Invalid_argument] if [src_pos] and [len] do not
```suggestion
   @raise Invalid_argument if [src_pos] and [len] do not
```

2019-10-08 11:42 UTC, Octachron commented
@dra27, removing the `Array` prefix  sounds like a good idea.

2019-10-08 23:07 UTC, foocraft commented
@dra27 Thank you for checking my PR and for explaining the rationale behind `ArrayLabels` referencing `Array` in the docs.

Do you think `ArrayLabels` should mention something about `StdLabels`? copy-pasting your example is tempting!

2019-10-09 07:35 UTC, dra27 commented
Thanks for the changes, @foocraft. The remaining thing is to remove all instances of `Array.` and `ArrayLabels.` from the documentation comments - looking at it, `ArrayLabels.` shouldn't appear anywhere and `Array.` should only be present in the `@@deprecated` attribute text.

It would be good to add some text at the top of the module explaining the usage, yes. I would move the `(** Array operations. *)` documentation comment to be before the array type and then expand it with the example - it'd be good if the description included a reference to the `StdLabels` module (i.e. `{!StdLabels}`). As a bonus, if you wanted, you could add that change to the other 3 modules 🙂

2019-10-14 18:10 UTC, foocraft commented
Hi @dra27, I've pushed some changes, not exactly sure if it's the right formatting style or not; more on that feedback would be great. For example, what's a good example code to put up there?

2019-10-15 08:58 UTC, dra27 approved these changes
This looks very nice to me - I've made rewording suggestions for the change to the headers which you *could* apply to the four of them if you wish.

Thanks for your time on this! @Octachron - please merge if you're happy, too

2019-10-15 08:58 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   This module is intended to be used through {!StdLabels} which would replace
```suggestion
   This module is intended to be used via {!StdLabels} which replaces
```

2019-10-15 08:58 UTC, dra27 commented on stdlib/arrayLabels.mli
> +   As an example usage:
```suggestion
   For example:
```

2019-10-15 09:49 UTC, foocraft commented
I updated across all files. Now it's more coherent :) Thanks for the suggestions.

2019-10-15 20:50 UTC, merged

2019-10-15 20:51 UTC, Octachron commented
Merged, thanks for the PR!