Fix bytecode backtrace generation when large integers are present.
ocaml/ocaml pull request #9271
Opened 2020-01-29 09:53 UTC by stedolan

#9268 again, since @jhjourdan noticed I only fixed half of the problem there.

2020-01-29 10:01 UTC, gasche commented
@jhjourdan Stephen wins by seven minutes. Would you review his version of your patch?

2020-01-29 10:06 UTC, jhjourdan requested changes

2020-01-29 10:06 UTC, jhjourdan commented on runtime/backtrace_byt.c
> +    value spv = (*sp)++;
`spv` is of type `value*`, right?
```suggestion
    value *spv = (*sp)++;
```

2020-01-29 10:06 UTC, jhjourdan commented on runtime/backtrace_byt.c
> +    if (Is_long(spv)) continue;
So it should be dereferenced here.
```suggestion
    if (Is_long(*spv)) continue;
```

2020-01-29 10:15 UTC, stedolan commented
> @jhjourdan Stephen wins by seven minutes.

The important thing, of course, is how soon the code is pushed. Building and/or working are optional!

2020-01-29 10:29 UTC, jhjourdan approved these changes
I think the code is now good to merge.

2020-01-31 07:49 UTC, gasche approved these changes
Approved on @jhjourdan's behalf. I will now merge and cherry-pick in 4.10 ( 368ee3cd74a80d5609a8bb7acae512001c7c5736 ).

2020-01-31 07:57 UTC, merged