Fix bug in best-fit on 32-bit
ocaml/ocaml pull request #9292
Opened 2020-02-10 12:06 UTC by lpw25

The code in best-fit for merging blocks that are larger than `Max_wosize` is broken. Technically this affects both 64-bit and 32-bit but in practice this only really shows up on 32 bit.

Without this PR:
```
$ cat foo.ml
let () =
  ignore (Array.init 5_000 (fun _ -> Array.make 10_000 0));
  Gc.full_major ()

$ ocamlopt foo.ml -o foo

$ ./foo

$ OCAMLRUNPARAM=a=2 ./foo
Segmentation fault (core dumped)
```

2020-02-10 12:07 UTC, lpw25 commented
I made this PR against the 4.10 branch because I think we should include it in 4.10.

2020-02-10 12:41 UTC, gasche commented
It would be nice to have a Changes entry and a regression test.

2020-02-10 14:05 UTC, jhjourdan requested changes
Well spotted!

I agree that this is a bug and that the fix should be correct.

Could you add a Changes entry and a test?

2020-02-10 14:35 UTC, lpw25 commented
Added a test and added this PR number to the best-fit Changes entry.

2020-02-10 14:43 UTC, gasche commented
@jhjourdan are you formally approving the PR? (I haven't done a review myself.)

2020-02-10 14:44 UTC, jhjourdan approved these changes
Thanks. This should be good to merge once CI passes.

2020-02-11 09:43 UTC, merged

2020-02-11 09:47 UTC, Octachron commented
Merged in 4.10 and cherry-picked on trunk as edabf2008cdf2e9130d42e9.