Export Filename.{Unix,Win32,Cygwin}
ocaml/ocaml pull request #9719
Opened 2020-06-29 05:31 UTC by xvw

Export submodules Unix, Win32 and Cygwin.
Fix #6287

2020-06-29 10:12 UTC, dra27 commented
I believe the original intent of this was also to expose `has_drive`. See, for example, https://gitlab.com/camlspotter/ocamlspot/-/blob/hg-default/filepath.ml#L40-46.

I spent some time on this a week or so ago thinking it would be quick and found quite a few bugs (especially in the Cygwin handling), which I'll push. The only problem with this as an interim step is that I don't think it actually fixes the original report's issue.

2020-06-29 11:04 UTC, xvw commented
@dra27 Yes you are right. I'm not very familar with "has_drive". So I've just remove the reference of "fix". Is that ok for you?

2020-06-29 11:24 UTC, nojb commented
Does `SYSDEPS` coincide with the full signature of the (current) `Filename` module? If yes, wouldn't it be better to `include SYSDEPS` in the interface of `Filename`?

2020-06-29 12:40 UTC, xvw commented
@nojb There is some small differences (`concat` is not in `SYSDEP` and `is_dir_sep` is not in the full API). The code could be reduced using a Functor but my goal in this PR was "only" to expose submodules. Do you think that I should (in this PR) go through a more ambitious refactoring?

2020-06-29 12:45 UTC, nojb commented
> @nojb There is some small differences (`concat` is not in `SYSDEP` and `is_dir_sep` is not in the full API). The code could be reduced using a Functor but my goal in this PR was "only" to expose submodules. Do you think that I should (in this PR) go through a more ambitious refactoring?

The problem is that we are stuck with any change in the `stdlib` more or less "forever", so we need to be careful. Personally, I think that if the objective of the PR is to simultaneously expose a version of `Filename` for each supported system, then using a common signature for the submodules and the "main" `Filename` module makes sense. But I haven't looked at the implementation and have no idea how difficult this is.

2020-07-03 16:42 UTC, xvw commented
@nojb Is it more like you thought about it?

2020-07-03 17:01 UTC, nojb requested changes
Thanks, this is what I had in mind. I left some suggestions, but in principle this looks good to me.

As this is a stdlib change, it would be better to have a second opinion a well. Perhaps @dra27 or @gasche can take a look?

2020-07-03 17:01 UTC, nojb commented on otherlibs/unix/unix.mli
> +   {!Filename.FILENAME.quote_command} is recommended.
The previous docstring is better, as 1) there is no value `Filename.FILENAME.quote_command`, and 2) the function that should be used is the one corresponding to the current system, so it is just `Filename.quote_command`.

2020-07-03 17:01 UTC, nojb commented on otherlibs/unix/unix.mli
> +   The {!Filename.FILENAME.quote_command} function can be used to
Idem.

2020-07-03 17:01 UTC, nojb commented on stdlib/filename.ml
> +  [@@ocaml.deprecated "Use Filename.get_temp_dir_name instead"]
As this one is deprecated, would it be difficult to only include it in the top-level module (for backwards-compatibility), but not in the new submodules?

2020-07-03 17:01 UTC, nojb commented on stdlib/filename.ml
> +module type FILENAME = sig
Should we call this signature `S`, by analogy to other existing modules in the standard library (`Hashtbl.S`, `Map.S`, ...)?

2020-07-03 17:01 UTC, nojb commented on stdlib/filename.ml
> +module Current =
Not very important, but you can just write `include` here instead of `module Current =`.

2020-07-03 17:01 UTC, nojb commented on stdlib/sys.mli
> +  The {!val:Filename.FILENAME.quote_command} performs the appropriate quoting
As with `Unix`, here the previous docstring is better.

2020-07-03 17:01 UTC, nojb commented on stdlib/filename.mli
> +    in {!val:extension}. If the extension is empty, the function
Have you checked that the generated `ocamldoc` looks OK?

2020-07-03 17:01 UTC, nojb commented on stdlib/filename.ml
> +  let prng = lazy(Random.State.make_self_init ())
This (and the two external above) could be put outside of the functor, I think.

2020-07-03 17:44 UTC, xvw commented on otherlibs/unix/unix.mli
> +   {!Filename.FILENAME.quote_command} is recommended.
It does not work (a warning is emitted) with OCamldoc.

2020-07-03 20:38 UTC, xvw commented on stdlib/filename.mli
> +    in {!val:extension}. If the extension is empty, the function
Yes (it refer Filename.FILENAME.extension).

2020-07-03 21:03 UTC, xvw commented on stdlib/filename.ml
> +  [@@ocaml.deprecated "Use Filename.get_temp_dir_name instead"]
Done

2020-07-03 21:03 UTC, xvw commented on stdlib/filename.ml
> +module type FILENAME = sig
Yes, you're right. Done.

2020-07-03 21:03 UTC, xvw commented on stdlib/filename.ml
> +module Current =
Done!

2020-07-03 21:04 UTC, xvw commented on stdlib/filename.ml
> +  let prng = lazy(Random.State.make_self_init ())
You're right, I've put the externals and prng outside of the functor. Thanks.

2020-07-03 21:18 UTC, xvw commented
There is still (in my point of view) a discussion point. Ocamldoc does not handle (correctly) inclusion (#7332). It is why I have to reference `Filename.S.f` instead of `Filename.f` and `S` is not expanded in the documentation of Filename, which can be confusing. Should I duplicate like this : 

```ocaml
module type S = sig 
    val f : a -> b 
    (** doc **)
end

val f : a -> b
(** doc **)
```

?

2020-07-04 07:14 UTC, nojb commented
> There is still (in my point of view) a discussion point. Ocamldoc does not handle (correctly) inclusion (#7332). It is why I have to reference `Filename.S.f` instead of `Filename.f` and `S` is not expanded in the documentation of Filename, which can be confusing.

Not sure how hard it would be, but I think it may be worth trying to generate the docs using `odoc` as well. This is because as I understand it, the plan is to switch to `odoc` for documentation in the not-too-distant future. cc @Octachron which will have more to say about this.

2020-07-04 11:02 UTC, xvw commented
Thanks @nojb, I have asked to @Octachron and he thought me that duplication is an acceptable compromise (until ODoc).
So I have duplicate Filename.S documentation in Filename (and removed "since" in Filename.S).

2020-07-04 14:39 UTC, dbuenzli commented
Could someone explain how these modules are supposed to be used by end users and/or what use case they intend to solve ? 

FWIW I had a similar PR recently on my `Fpath` module and I think that simply exposing these interfaces is really not the right way to go on about the problem. 

I think it may be worth pondering the comment I made [there](https://github.com/dbuenzli/fpath/pull/13#issuecomment-645938375). One thing that is obviously different in `Filename` is that it has no abstract type but the problem (and answers I try to give there) remains the same. 

It all starts with asking you the question how are you going to know which kind of path your are handling and thus which of the modules you have to use ?

2020-07-04 19:01 UTC, nojb commented
> It all starts with asking you the question how are you going to know which kind of path your are handling and thus which of the modules you have to use ?

Thanks for chiming in, and asking a very good question. Just to clarify my position, I am not convinced the PR should be merged, but *if* we were to merge it, then my point was that the submodules should have the same signature as the existing `Filename` module.

Having said that, if I wanted to argue for inclusion, I would put forward the case of working in mixed environments, for example, when you need to call Cygwin executables from a native Windows port (or the other way around), or calling native Windows programs from inside WSL port. The user is assumed to know the expected encoding of the paths she is building in each case. The point of the PR is to make it possible, *under this assumption*, to use the right function to, say, quote a program argument.

But I agree that the exposed API is not a full solution to the problem of handling and mixing paths between different systems. Personally I am not aware of any satisfactory API to solve this problem in other languages, but would love to hear otherwise.

Given all this, the question seems to be: do we want to go ahead and expose these submodules for the convenience in those few situations where one knows exactly the conventions of every path in sight, or do we consider that exposing these submodules is akin to exposing a kind of "unsafe" API that will do more harm than good?

In my experience, the opportunities where I would have made use of these submodules where few and far between, so I think it would be perfectly reasonable to wait instead until a better API comes along.

2020-07-06 08:51 UTC, xvw commented
@Et7f3 yes, I think it is fixed on the last commit?

My goal with this PR was to solve #6287. But it is maybe not very useful so should I close the PR?

2020-07-06 09:36 UTC, Et7f3 commented
Ah sorry I haven't seen this PR: just see my commit cherry-pick and notified space. Yes it is fixed. Sorry for the noise. (btw their is also some whitespace change, but I don't know the policy of this repo about whitespace change)

> so should I close the PR?

No!! This is a useful PR.

2020-07-06 09:49 UTC, xvw commented
I think whitspace change are present because I move the content of the module in a submodule.

2020-07-06 09:51 UTC, nojb commented
> My goal with this PR was to solve #6287. But it is maybe not very useful so should I close the PR?

I would suggest to give some time for other developers to chime in before taking any decision. Thanks!

2020-07-06 17:02 UTC, hcarty commented
> the case of working in mixed environments, for example, when you need to call Cygwin executables from a native Windows port (or the other way around), or calling native Windows programs from inside WSL port. The user is assumed to know the expected encoding of the paths she is building in each case. The point of the PR is to make it possible, under this assumption, to use the right function to, say, quote a program argument.

This is a case I run into in the real world. While it doesn't happen frequently it is very challenging to deal with given the current stdlib and OCaml library ecosystem.

I understand @dbuenzli's concerns about this exposing an incomplete API.  However, without this a lot of the useful tools to build a more complete API exist in OCaml but are hidden from users.  Exposing these platform-specific modules makes it easier for the community to experiment with higher level logic built on top of `Filename` and addresses the case(s) @nojb mentioned where a user knows the environment a path is targeting.

I would argue for including this PR because it unblocks a real world use case without introducing lots of new code and it makes it easier for users to build more sophisticated APIs if those APIs are deemed useful.

2020-07-06 18:46 UTC, dbuenzli commented
> I understand @dbuenzli's concerns about this exposing an incomplete API.

My concern is not about exposing an incomplete API it's about exposing a wrong model that the stdlib will have to support for ages.

> I would argue for including this PR because it unblocks a real world use case without introducing lots of new code and it makes it easier for users to build more sophisticated APIs if those APIs are deemed useful.

As far as I can see, the stdlib evolution tends to work the other way round, once it is sure something works and is needed somewhat pervasively, or solves a library interoperability problem, the case is made for introduction. It's perfectly possible to experiment with this outside the stdlib without this PR, even more so as `Filename` exposes no abstract type.

Someone has to come up with a design and experiment with it, bulk exposing library internals is not going to magically solve the problem. I have sketched one in the `fpath` PR I mentioned earlier, I currently don't have the need for it and no money to invest to develop it myself. But I'm happy to integrate the work in `fpath` from anyone interested in following the ideas outlined there.

2020-08-07 10:17 UTC, xvw commented
Since the API is incomplete. I suggest to close the PR.
Thanks for your reviews and your insights!

2020-08-07 10:17 UTC, closed without merging